<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Simple linear regression: formalizing concepts – STAT 155</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../activities/01_foundations_welcome.html">Activities</a></li><li class="breadcrumb-item"><a href="../activities/04_slr_formalization.html">Simple linear regression: formalizing concepts</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">STAT 155</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Activities</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/01_foundations_welcome.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Fundamentals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/02_foundations_univariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Univariate visualization and summaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/03_slr_introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple linear regression: Visualization and Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/04_slr_formalization.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Simple linear regression: formalizing concepts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/05_slr_model_eval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple linear regression: model evaluation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/06_slr_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple linear regression: Transformations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/07_slr_cat_predictor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple linear regression: categorical predictor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/08_mlr_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to multiple regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/09_mlr_principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple regression principles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/10_mlr_confounding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Confounding variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/11_mlr_interaction_explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple linear regression: exploring interaction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/12_mlr_interaction_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple linear regression: interaction terms practice</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/13_mlr_model_building_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple linear regression: model building (part 1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/14_mlr_model_building_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple linear regression: model building (part 2)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/15_prob_odds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability and Odds</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/16_logistic_univariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/17_logistic_multivariate_evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/18_sampling_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Normal model &amp; sampling variation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/19_sampling_dist_clt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sampling distributions &amp; the CLT</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/20_bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrapping</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/21_confidence_intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/22_hypothesis_testing_discovery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis testing: discovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/23_hypothesis_testing_details.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis testing details</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/24_hypothesis_testing_considerations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis testing: additional considerations</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Homework</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 8</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../r_resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Resources</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#notes" id="toc-notes" class="nav-link active" data-scroll-target="#notes">Notes</a>
  <ul class="collapse">
  <li><a href="#learning-goals" id="toc-learning-goals" class="nav-link" data-scroll-target="#learning-goals">Learning goals</a></li>
  <li><a href="#readings-and-videos" id="toc-readings-and-videos" class="nav-link" data-scroll-target="#readings-and-videos">Readings and videos</a></li>
  <li><a href="#review" id="toc-review" class="nav-link" data-scroll-target="#review">Review</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
  <li><a href="#exercise-1-get-to-know-the-data" id="toc-exercise-1-get-to-know-the-data" class="nav-link" data-scroll-target="#exercise-1-get-to-know-the-data">Exercise 1: Get to know the data</a></li>
  <li><a href="#exercise-2-get-to-know-the-outcomeresponse-variable" id="toc-exercise-2-get-to-know-the-outcomeresponse-variable" class="nav-link" data-scroll-target="#exercise-2-get-to-know-the-outcomeresponse-variable">Exercise 2: Get to know the outcome/response variable</a></li>
  <li><a href="#exercise-3-explore-the-relationship-between-ridership-and-temperature" id="toc-exercise-3-explore-the-relationship-between-ridership-and-temperature" class="nav-link" data-scroll-target="#exercise-3-explore-the-relationship-between-ridership-and-temperature">Exercise 3: Explore the relationship between ridership and temperature</a></li>
  <li><a href="#exercise-4-filtering-our-data" id="toc-exercise-4-filtering-our-data" class="nav-link" data-scroll-target="#exercise-4-filtering-our-data">Exercise 4: Filtering our data</a></li>
  <li><a href="#exercise-5-model-fitting-and-coefficient-interpretation" id="toc-exercise-5-model-fitting-and-coefficient-interpretation" class="nav-link" data-scroll-target="#exercise-5-model-fitting-and-coefficient-interpretation">Exercise 5: Model fitting and coefficient interpretation</a></li>
  <li><a href="#exercise-6-predictions-and-residuals" id="toc-exercise-6-predictions-and-residuals" class="nav-link" data-scroll-target="#exercise-6-predictions-and-residuals">Exercise 6: Predictions and residuals</a></li>
  <li><a href="#exercise-7-changing-temperature-units-challenge" id="toc-exercise-7-changing-temperature-units-challenge" class="nav-link" data-scroll-target="#exercise-7-changing-temperature-units-challenge">Exercise 7: Changing temperature units (CHALLENGE)</a></li>
  <li><a href="#reflection" id="toc-reflection" class="nav-link" data-scroll-target="#reflection">Reflection</a></li>
  <li><a href="#render-your-work" id="toc-render-your-work" class="nav-link" data-scroll-target="#render-your-work">Render your work</a></li>
  </ul></li>
  <li><a href="#additional-practice" id="toc-additional-practice" class="nav-link" data-scroll-target="#additional-practice">Additional Practice</a>
  <ul class="collapse">
  <li><a href="#exercise-8-ridership-and-windspeed" id="toc-exercise-8-ridership-and-windspeed" class="nav-link" data-scroll-target="#exercise-8-ridership-and-windspeed">Exercise 8: Ridership and windspeed</a></li>
  <li><a href="#exercise-9-data-drills-filter-select-summarize" id="toc-exercise-9-data-drills-filter-select-summarize" class="nav-link" data-scroll-target="#exercise-9-data-drills-filter-select-summarize">Exercise 9: Data drills (<code>filter</code>, <code>select</code>, <code>summarize</code>)</a>
  <ul class="collapse">
  <li><a href="#verb-1-summarize" id="toc-verb-1-summarize" class="nav-link" data-scroll-target="#verb-1-summarize">Verb 1: <code>summarize</code></a></li>
  <li><a href="#verb-2-select" id="toc-verb-2-select" class="nav-link" data-scroll-target="#verb-2-select">Verb 2: <code>select</code></a></li>
  <li><a href="#verb-3-filter" id="toc-verb-3-filter" class="nav-link" data-scroll-target="#verb-3-filter">Verb 3: <code>filter</code></a></li>
  </ul></li>
  <li><a href="#exercise-10-your-turn" id="toc-exercise-10-your-turn" class="nav-link" data-scroll-target="#exercise-10-your-turn">Exercise 10: Your turn</a></li>
  </ul></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions">Solutions</a>
  <ul class="collapse">
  <li><a href="#exercise-1-get-to-know-the-data-1" id="toc-exercise-1-get-to-know-the-data-1" class="nav-link" data-scroll-target="#exercise-1-get-to-know-the-data-1">Exercise 1: Get to know the data</a></li>
  <li><a href="#exercise-2-get-to-know-the-outcomeresponse-variable-1" id="toc-exercise-2-get-to-know-the-outcomeresponse-variable-1" class="nav-link" data-scroll-target="#exercise-2-get-to-know-the-outcomeresponse-variable-1">Exercise 2: Get to know the outcome/response variable</a></li>
  <li><a href="#exercise-3-explore-the-relationship-between-ridership-and-temperature-1" id="toc-exercise-3-explore-the-relationship-between-ridership-and-temperature-1" class="nav-link" data-scroll-target="#exercise-3-explore-the-relationship-between-ridership-and-temperature-1">Exercise 3: Explore the relationship between ridership and temperature</a></li>
  <li><a href="#exercise-4-filtering-our-data-1" id="toc-exercise-4-filtering-our-data-1" class="nav-link" data-scroll-target="#exercise-4-filtering-our-data-1">Exercise 4: Filtering our data</a></li>
  <li><a href="#exercise-5-model-fitting-and-coefficient-interpretation-1" id="toc-exercise-5-model-fitting-and-coefficient-interpretation-1" class="nav-link" data-scroll-target="#exercise-5-model-fitting-and-coefficient-interpretation-1">Exercise 5: Model fitting and coefficient interpretation</a></li>
  <li><a href="#exercise-6-predictions-and-residuals-1" id="toc-exercise-6-predictions-and-residuals-1" class="nav-link" data-scroll-target="#exercise-6-predictions-and-residuals-1">Exercise 6: Predictions and residuals</a></li>
  <li><a href="#exercise-7-changing-temperature-units-challenge-1" id="toc-exercise-7-changing-temperature-units-challenge-1" class="nav-link" data-scroll-target="#exercise-7-changing-temperature-units-challenge-1">Exercise 7: Changing temperature units (CHALLENGE)</a></li>
  <li><a href="#exercise-8-ridership-and-windspeed-1" id="toc-exercise-8-ridership-and-windspeed-1" class="nav-link" data-scroll-target="#exercise-8-ridership-and-windspeed-1">Exercise 8: Ridership and windspeed</a></li>
  <li><a href="#exercise-9-data-drills-filter-select-summarize-1" id="toc-exercise-9-data-drills-filter-select-summarize-1" class="nav-link" data-scroll-target="#exercise-9-data-drills-filter-select-summarize-1">Exercise 9: Data drills (<code>filter</code>, <code>select</code>, <code>summarize</code>)</a>
  <ul class="collapse">
  <li><a href="#verb-1-summarize-1" id="toc-verb-1-summarize-1" class="nav-link" data-scroll-target="#verb-1-summarize-1">Verb 1: <code>summarize</code></a></li>
  <li><a href="#verb-2-select-1" id="toc-verb-2-select-1" class="nav-link" data-scroll-target="#verb-2-select-1">Verb 2: <code>select</code></a></li>
  <li><a href="#verb-3-filter-1" id="toc-verb-3-filter-1" class="nav-link" data-scroll-target="#verb-3-filter-1">Verb 3: <code>filter</code></a></li>
  </ul></li>
  <li><a href="#exercise-10-your-turn-1" id="toc-exercise-10-your-turn-1" class="nav-link" data-scroll-target="#exercise-10-your-turn-1">Exercise 10: Your turn</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../activities/01_foundations_welcome.html">Activities</a></li><li class="breadcrumb-item"><a href="../activities/04_slr_formalization.html">Simple linear regression: formalizing concepts</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Simple linear regression: formalizing concepts</h1>
<p class="subtitle lead">Notes and in-class exercises</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="notes" class="level1">
<h1>Notes</h1>
<ul>
<li>You can download a template file to work with <a href="../activity_templates/04_slr_formalization.qmd">here</a>.</li>
<li><strong>File organization:</strong> Save this file in the “Activities” subfolder of your “STAT155” folder.</li>
</ul>
<section id="learning-goals" class="level2">
<h2 class="anchored" data-anchor-id="learning-goals">Learning goals</h2>
<p>By the end of this lesson, you should be able to:</p>
<ul>
<li>Differentiate between a <strong>response</strong> / <strong>outcome variable</strong> and a <strong>predictor</strong> / <strong>explanatory variable</strong></li>
<li>Write a <strong>model formula</strong> for a simple linear regression model with a quantitative predictor</li>
<li>Write R code to fit a linear regression model</li>
<li>Interpret the <strong>intercept</strong> and <strong>slope</strong> coefficients in a simple linear regression model with a quantitative predictor</li>
<li>Compute <strong>expected / predicted / fitted values</strong> and <strong>residuals</strong> from a linear regression model formula</li>
<li>Interpret predicted values and residuals in the context of the data</li>
<li>Explain the connection between residuals and the <strong>least squares criterion</strong></li>
</ul>
</section>
<section id="readings-and-videos" class="level2">
<h2 class="anchored" data-anchor-id="readings-and-videos">Readings and videos</h2>
<p>Before class you should have read and/or watched:</p>
<ul>
<li>Reading: Sections 2.8, 3.1-3.3, 3.6 in the <a href="https://mac-stat.github.io/Stat155Notes/">STAT 155 Notes</a></li>
<li>Videos:
<ul>
<li><a href="https://voicethread.com/share/14942266/">Summarizing the Relationships between Two Quantitative Variables</a> (Time: 12:12)</li>
<li><a href="https://voicethread.com/share/14927659/">Introduction to Linear Models</a> (Time: 10:57)</li>
<li><a href="https://voicethread.com/share/14980221/">Method of Least Squares</a> (Time: 5:10)</li>
<li><a href="https://voicethread.com/share/15148106/">Interpretation of Intercept and Slope</a> (Time: 11:09)</li>
<li><a href="https://voicethread.com/share/14928147/">R Code for Fitting a Linear Model</a> (Time: 11:07)</li>
</ul></li>
</ul>
</section>
<section id="review" class="level2">
<h2 class="anchored" data-anchor-id="review">Review</h2>
<p>Last class we were looking at powerlifting data.</p>
<blockquote class="blockquote">
<p><strong>Guiding question:</strong> Are bigger (heavier) lifters stronger for their weight (SWR = total lifted/bodyweight)?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages and import data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>lifts <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://mac-stat.github.io/data/powerlifting.csv"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>lifts <span class="ot">&lt;-</span> lifts <span class="sc">%&gt;%</span> </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">SWR =</span> TotalKg<span class="sc">/</span>BodyweightKg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lifts, <span class="fu">aes</span>(<span class="at">x =</span> BodyweightKg, <span class="at">y =</span> SWR)) <span class="sc">+</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 8752 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 8752 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_slr_formalization_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li>The relationship looks slightly curved: positively correlated at first and then negatively correlated afterward.</li>
<li>The strong positive slope at the beginning and strong negative slope at the end are caused by a few outlier observations and are less trustworthy.
<ul>
<li>The height of the gray band around the blue trend represents uncertainty about the value of the blue line at that location. The band is thicker towards the ends of the plot.</li>
</ul></li>
<li>There may be a slightly positive relationship between 50kg and 80kg, but afterward the relationship looks clearly negative.</li>
</ul>
<p>A natural next question to ask is:</p>
<blockquote class="blockquote">
<p>How steep are the upsloping and downsloping parts of this trend?</p>
</blockquote>
<p>Because our pre-class material focused on single lines as models, let’s focus on the downslope.</p>
<p><br><br><br><br></p>
<p>We can focus on lifters above 80kg using the <code>filter()</code> function from the <code>dplyr</code> package for data wrangling. <code>filter()</code> selectively keeps rows based on a condition:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lifts_subs <span class="ot">&lt;-</span> lifts <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(BodyweightKg <span class="sc">&gt;</span> <span class="dv">80</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s look at the relationship again with a linear smoothing line (a <strong>line of best fit</strong>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lifts_subs, <span class="fu">aes</span>(<span class="at">x =</span> BodyweightKg, <span class="at">y =</span> SWR)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 3863 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 3863 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_slr_formalization_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The line is governed by a formula that looks like:</p>
<p><span class="math display">\[
y = a + bx
\]</span></p>
<p>We can rewrite that formula for our context, where SWR is our <strong>outcome</strong> or <strong>response</strong> variable (the variable we’re interested in explaining) and BodyweightKg is a <strong>predictor</strong> or <strong>explanatory variable</strong>:</p>
<p><span class="math display">\[
\text{SWR} = a + b \,\text{BodyweightKg}
\]</span></p>
<p>“Best” is determined by the <strong>least squares criterion</strong>: we find the values of <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> such that we <strong>minimize the sum of squared residuals</strong>. A <strong>residual</strong> is the vertical distance from a point to the line:</p>
<p><span class="math display">\[
\text{residual} = \text{observed y} - \text{predicted y}
\]</span></p>
<p>In other words, a residual quantifies the error in our model. The idea with the least squares criterion is that we want our line to minimize these errors.</p>
<p><br><br><br><br></p>
<p>Note that we will be writing the formula for our line in a slightly different way. Instead of:</p>
<p><span class="math display">\[
\text{SWR} = a + b \,\text{BodyweightKg}
\]</span></p>
<p>We will be writing model formula as such:</p>
<p><span class="math display">\[
E[\text{SWR} \mid \text{BodyweightKg}] = \beta_0 + \beta_1\text{BodyweightKg}
\]</span></p>
<ul>
<li>The <span class="math inline">\(E[]\)</span> is read as “expected value” which is another way to describe the average value.
<ul>
<li>Expected value is important in describing our line because our line describes the trend in our data <em>on average</em>. It does not describe what to expect for any individual case.</li>
</ul></li>
<li>The <span class="math inline">\(E[\text{SWR} \mid \text{BodyweightKg}]\)</span> part is read as “expected value of SWR given body weight”. This is saying that the average value of SWR is function of body weight.</li>
<li>The expected value shows up in the way that we interpret the intercept and slope in our line:
<ul>
<li>Intercept <span class="math inline">\(\beta_0\)</span>: The average SWR for someone who weights 0kg. (Not meaningful! But the intercept is important for placing our line vertically)</li>
<li>Slope <span class="math inline">\(\beta_1\)</span>: Every 1kg increase in body weight is linked with a <span class="math inline">\(\beta_1\)</span> change in SWR on average.</li>
</ul></li>
</ul>
<p>Let’s see these interpretations with numbers:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(SWR <span class="sc">~</span> BodyweightKg, <span class="at">data =</span> lifts_subs)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(mod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate   Std. Error   t value      Pr(&gt;|t|)
(Intercept)   6.44448472 0.0571735021 112.71803  0.000000e+00
BodyweightKg -0.02046372 0.0005710373 -35.83604 1.538229e-277</code></pre>
</div>
</div>
<ul>
<li>The “Estimate” column contains the estimated coefficients in our model (the intercept and slope).
<ul>
<li>Full model formula: <span class="math inline">\(E[\text{SWR} \mid \text{BodyweightKg}] = 6.44 - 0.02\,\text{BodyweightKg}\)</span></li>
<li>Intercept <span class="math inline">\(\beta_0\)</span>: The average SWR for someone who weights 0kg is 6.44. (Not meaningful! No one weighs 0kg!)</li>
<li>Slope <span class="math inline">\(\beta_1\)</span>: Every 1kg increase in body weight is linked with a 0.02 decrease in SWR. So a 10kg increase in body weight is linked with a 0.2 decrease in SWR on average. <strong>Interpreting this coefficient addresses our guiding question.</strong></li>
</ul></li>
<li>Key features of slope interpretation:
<ul>
<li><strong>Units:</strong> Provided units of kg for the predictor. Note that there are no units for SWR because we’re dividing kilograms lifted by kilograms of body weight.</li>
<li><strong>Averages vs.&nbsp;individuals:</strong> <em>On average</em> lifters who differ by 1kg in body weight will differ in SWR by 0.02, but any given pair of lifters who differ by 1kg in body weight will not always differ in SWR by 0.02.</li>
<li><strong>Causal language:</strong> We want to be careful to not say “Increasing your body weight by 1 kg will decrease your SWR by 0.02 on average” because there may be other factors at play.
<ul>
<li>For example, maybe heavier lifters tend to also use equipment that helps them lift more while lighter lifters don’t.</li>
<li>This might make heavier lifters seem stronger than they are.</li>
<li>When accounting for equipment usage, the relationship between body weight and SWR might change.</li>
</ul></li>
</ul></li>
</ul>
<p><br><br><br><br></p>
<p>We can use our estimated model formula to get <strong>predictions</strong> and <strong>residuals</strong>.</p>
<p>What would we expect the SWR to be for a lifter who weighs 100kg? (On average, what is the SWR for a 100kg lifter?)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fl">6.44</span> <span class="sc">-</span> <span class="fl">0.02</span> <span class="sc">*</span> <span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.44</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>On average, a lifter who weighs 100kg is expected to have a SWR of 4.44.</p>
</blockquote>
<p>Suppose that Alice is a 100kg lifter who has a SWR of 5.5. What would her residual be?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># residual = observed y - predicted y</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fl">5.5</span> <span class="sc">-</span> <span class="fl">4.44</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.06</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>We <strong>underpredict</strong> Alice’s SWR by 1.06.</p>
</blockquote>
<p><br><br><br><br></p>
</section>
</section>
<section id="exercises" class="level1">
<h1>Exercises</h1>
<p><strong>Context:</strong> Today we’ll explore data from <a href="https://capitalbikeshare.com/">Capital Bikeshare</a>, a company in Washington DC. Our main goal will be to explore daily ridership among registered users, as measured by <code>riders_registered</code>. Read in the data below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages and import data</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>bikes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://mac-stat.github.io/data/bikeshare.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exercise-1-get-to-know-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1-get-to-know-the-data">Exercise 1: Get to know the data</h2>
<p>Create a new code chunk to look at the first few rows of the data and learn how much data (in terms of cases and variables) we have.</p>
<ol type="a">
<li>What does a case represent?</li>
<li>How many and what kinds of variables do we have?</li>
<li>Thinking about the who, what, when, where, why, and how of this data, which of the 5W’s + H seem most relevant to our investigations? Explain your thoughts.</li>
</ol>
</section>
<section id="exercise-2-get-to-know-the-outcomeresponse-variable" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2-get-to-know-the-outcomeresponse-variable">Exercise 2: Get to know the outcome/response variable</h2>
<p>Let’s get acquainted with the <code>riders_registered</code> variable.</p>
<ul>
<li>Construct an appropriate plot to visualize the distribution of this variable, and compute appropriate numerical summaries.</li>
<li>Write a good paragraph interpreting the plot and numerical summaries.</li>
</ul>
</section>
<section id="exercise-3-explore-the-relationship-between-ridership-and-temperature" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3-explore-the-relationship-between-ridership-and-temperature">Exercise 3: Explore the relationship between ridership and temperature</h2>
<p>We’d like to understand how daily ridership among registered users relates with the temperature that it feels like that day (<code>temp_feel</code>).</p>
<ol type="a">
<li>What type of plot would be appropriate to visualize this relationship? Sketch and describe what you expect this plot to look like.</li>
<li>Create an appropriate plot using <code>ggplot()</code>. How does the plot compare to what you predicted?</li>
<li>Add the following two lines after your plot to add a linear (blue) and curved (red) smoothing line. What do you notice? Is a simple linear regression model appropriate for this data?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a red straight line of best fit and a blue curve of best fit</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>YOUR_PLOT <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercise-4-filtering-our-data" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4-filtering-our-data">Exercise 4: Filtering our data</h2>
<p>The relationship between registered riders and temperature looks linear below 80 degrees. We can use the <code>filter()</code> function from the <code>dplyr</code> package to subset our cases. (We’ll learn techniques soon for handling this nonlinear relationship.)</p>
<p>If we wanted to only keep cases where registered ridership was greater than 2000, we would use the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The %&gt;% is called a "pipe" and feeds what comes before it</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># into what comes after (bikes data is "fed into" the filter() function)</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>NEW_DATASET_NAME <span class="ot">&lt;-</span> bikes <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(riders_registered <span class="sc">&gt;</span> <span class="dv">2000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Adapt the example above to create a new dataset called <code>bikes_sub</code> that only keeps cases where the felt temperature is less than 80 degrees.</p>
</section>
<section id="exercise-5-model-fitting-and-coefficient-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5-model-fitting-and-coefficient-interpretation">Exercise 5: Model fitting and coefficient interpretation</h2>
<p>Let’s fit a simple linear regression model and examine the results. Step through code chunk slowly, and make note of new code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct and save the model as bike_mod</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># What's the purpose of "riders_registered ~ temp_feel"?</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># What's the purpose of "data = bikes_sub"?</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>bike_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(riders_registered <span class="sc">~</span> temp_feel, <span class="at">data =</span> bikes_sub)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A long summary of the model stored in bike_mod</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bike_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A simplified model summary</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(bike_mod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="a">
<li><p>Using the model summary output, complete the following model formula:<br>
E[riders_registered | temp_feel] = ___ + ___ * temp_feel</p></li>
<li><p>Interpret the intercept in terms of the data context. <em>Make sure to use non-causal language, include units, and talk about averages rather than individual cases.</em> Is the intercept meaningful in this situation?</p></li>
<li><p>Interpret the slope in terms of the data context. <em>Make sure to use non-causal language, include units, and talk about averages rather than individual cases.</em></p></li>
</ol>
</section>
<section id="exercise-6-predictions-and-residuals" class="level2">
<h2 class="anchored" data-anchor-id="exercise-6-predictions-and-residuals">Exercise 6: Predictions and residuals</h2>
<p>On August 17, 2012, the <code>temp_feel</code> was 53.816 degrees and there were 5665 riders. We can get data for this day using the <code>filter()</code> and <code>select()</code> <code>dplyr</code> functions. Note, but don’t worry about the syntax – we haven’t learned this yet:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>bikes_sub <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(date <span class="sc">==</span> <span class="st">"2012-08-17"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(riders_registered, temp_feel) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="a">
<li><p>Peak back at the scatterplot. Identify which point corresponds to August 17, 2012. Is it close to the trend? Were there <em>more</em> riders than expected or <em>fewer</em> than expected?</p></li>
<li><p>Use your model formula from the previous exercise to <em>predict</em> the ridership on August 17, 2012 from the temperature on that day. (That is, where do days with this temperature fall on the model trend line? How many registered riders would we <em>expect</em> on a 53.816 degree day?)</p></li>
<li><p>Check your part b calculation using the <code>predict()</code> function. Take careful note of the syntax – there’s a lot going on!</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What is the purpose of newdata = ___???</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(bike_mod, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">temp_feel =</span> <span class="fl">53.816</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="4" type="a">
<li><p>Calculate the <strong>residual</strong> or <strong>prediction error</strong>. How far does the <em>observed</em> ridership fall from the <em>model prediction</em>?</p>
<p>residual = observed y - predicted y = ???</p></li>
<li><p>Are positive residuals above or below the trend line? When we have positive residuals, does the model over- or under-estimate ridership? Repeat these questions for negative residuals.</p></li>
<li><p>For an 85 degree day, how many registered riders would we expect? Do you think it’s a good idea to make this prediction? (Revisit the visualization and filtering we did in Exercises 3 and 4.)</p></li>
</ol>
</section>
<section id="exercise-7-changing-temperature-units-challenge" class="level2">
<h2 class="anchored" data-anchor-id="exercise-7-changing-temperature-units-challenge">Exercise 7: Changing temperature units (CHALLENGE)</h2>
<p>Suppose we had measured temperature in degrees Celsius rather than degrees Fahrenheit. How do you think our intercept and slope estimates, and their coefficient interpretations, would change?</p>
</section>
<section id="reflection" class="level2">
<h2 class="anchored" data-anchor-id="reflection">Reflection</h2>
<p>Statistics is a particular kind of language and collection of tools for channeling <strong>curiosity</strong> to improve our world.</p>
<p>Review the learning objectives at the top of this file and the flow of today’s activity. How do the concepts we practiced today facilitate curiosity?</p>
<blockquote class="blockquote">
<p><strong>Response:</strong> Put your response here.</p>
</blockquote>
</section>
<section id="render-your-work" class="level2">
<h2 class="anchored" data-anchor-id="render-your-work">Render your work</h2>
<ul>
<li>Click the “Render” button in the menu bar for this pane (blue arrow pointing right). This will create an HTML file containing all of the directions, code, and responses from this activity. A preview of the HTML will appear in the browser.</li>
<li>Scroll through and inspect the document to check that your work translated to the HTML format correctly.</li>
<li>Close the browser tab.</li>
<li>Go to the “Background Jobs” pane in RStudio and click the Stop button to end the rendering process.</li>
<li>Navigate to your “Activities” subfolder within your “STAT155” folder and locate the HTML file. You can open it again in your browser to double check.</li>
</ul>
</section>
</section>
<section id="additional-practice" class="level1">
<h1>Additional Practice</h1>
<section id="exercise-8-ridership-and-windspeed" class="level2">
<h2 class="anchored" data-anchor-id="exercise-8-ridership-and-windspeed">Exercise 8: Ridership and windspeed</h2>
<p>Let’s pull together everything that you’ve practiced in the preceding exercises to investigate the relationship between <code>riders_registered</code> and <code>windspeed</code>. Go back to using the <code>bikes</code> dataset (instead of <code>bikes_sub</code>) because we no longer need to only keep days less than 80 degrees.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct and interpret a visualization of this relationship</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Include a representation of the relationship trend</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Use lm to construct a model of riders_registered vs windspeed</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Save this as bike_mod2</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a short summary of this model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="a">
<li>Summarize your observations from the visualizations.</li>
<li>Write out a formula for the model trend.</li>
<li>Interpret both the intercept and the windspeed coefficient. (Note: What does a negative slope indicate?)</li>
<li>Use this model to predict the ridership on August 17, 2012 and calculate the corresponding residual. (Note: You’ll first need to find the windspeed on this date!)</li>
</ol>
</section>
<section id="exercise-9-data-drills-filter-select-summarize" class="level2">
<h2 class="anchored" data-anchor-id="exercise-9-data-drills-filter-select-summarize">Exercise 9: Data drills (<code>filter</code>, <code>select</code>, <code>summarize</code>)</h2>
<p>This exercise is designed to help you keep building your <code>dplyr</code> skills. These skills are important to data cleaning and digging, which in turn is important to really making meaning of our data. We’ll work with a simpler set of 10 data points:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="ot">&lt;-</span> bikes <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(date, temp_feel, humidity, riders_registered, day_of_week) <span class="sc">%&gt;%</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="verb-1-summarize" class="level3">
<h3 class="anchored" data-anchor-id="verb-1-summarize">Verb 1: <code>summarize</code></h3>
<p>Thus far, in the <code>dplyr</code> grammar you’ve seen 3 <strong>verbs</strong> or action words: <code>summarize()</code>, <code>select()</code>, <code>filter()</code>. Try out the following code and then summarize the point of the <code>summarize()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="fu">mean</span>(temp_feel), <span class="fu">mean</span>(humidity))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="verb-2-select" class="level3">
<h3 class="anchored" data-anchor-id="verb-2-select">Verb 2: <code>select</code></h3>
<p>Try out the following code and then summarize the point of the <code>select()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(date, temp_feel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>date, <span class="sc">-</span>temp_feel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="verb-3-filter" class="level3">
<h3 class="anchored" data-anchor-id="verb-3-filter">Verb 3: <code>filter</code></h3>
<p>Try out the following code and then summarize the point of the <code>filter()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(riders_registered <span class="sc">&gt;</span> <span class="dv">850</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(day_of_week <span class="sc">==</span> <span class="st">"Sat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(riders_registered <span class="sc">&gt;</span> <span class="dv">850</span>, day_of_week <span class="sc">==</span> <span class="st">"Sat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="exercise-10-your-turn" class="level2">
<h2 class="anchored" data-anchor-id="exercise-10-your-turn">Exercise 10: Your turn</h2>
<p>Use <code>dplyr</code> verbs to complete each task below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only information about the humidity and day of week</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only information about the humidity and day of week using a different approach</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only information for Sundays</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only information for Sundays with temperatures below 50</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the maximum and minimum temperatures</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br><br><br><br><br></p>
</section>
</section>
<section id="solutions" class="level1">
<h1>Solutions</h1>
<section id="exercise-1-get-to-know-the-data-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1-get-to-know-the-data-1">Exercise 1: Get to know the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(bikes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 731  15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bikes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 15
  date       season  year month day_of_week weekend holiday temp_actual
  &lt;date&gt;     &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;       &lt;lgl&gt;   &lt;chr&gt;         &lt;dbl&gt;
1 2011-01-01 winter  2011 Jan   Sat         TRUE    no             57.4
2 2011-01-02 winter  2011 Jan   Sun         TRUE    no             58.8
3 2011-01-03 winter  2011 Jan   Mon         FALSE   no             46.5
4 2011-01-04 winter  2011 Jan   Tue         FALSE   no             46.8
5 2011-01-05 winter  2011 Jan   Wed         FALSE   no             48.7
6 2011-01-06 winter  2011 Jan   Thu         FALSE   no             47.1
# ℹ 7 more variables: temp_feel &lt;dbl&gt;, humidity &lt;dbl&gt;, windspeed &lt;dbl&gt;,
#   weather_cat &lt;chr&gt;, riders_casual &lt;dbl&gt;, riders_registered &lt;dbl&gt;,
#   riders_total &lt;dbl&gt;</code></pre>
</div>
</div>
<ol type="a">
<li>A case represents a day of the year.</li>
<li>We have 15 variables broadly concerning weather, day of week information, whether the day is a holiday.</li>
<li>Lots of answers are reasonable here! When and where seem to be particularly relevant because this is for a rideshare based in Washington DC with data from 2011-2012. Ridership likely changes a lot from city to city and over time.</li>
</ol>
</section>
<section id="exercise-2-get-to-know-the-outcomeresponse-variable-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2-get-to-know-the-outcomeresponse-variable-1">Exercise 2: Get to know the outcome/response variable</h2>
<p>The distribution of the <code>riders_registered</code> variable looks fairly symmetric. On average there are about 3600 registered riders per day (mean = 3656, median = 3662). On any given day, the number of registered riders is about 1560 from the mean. There seem to be a small number of low outliers (minimum ridership was 20).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bikes, <span class="fu">aes</span>(<span class="at">x =</span> riders_registered)) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_slr_formalization_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bikes, <span class="fu">aes</span>(<span class="at">y =</span> riders_registered)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_slr_formalization_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bikes<span class="sc">$</span>riders_registered)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
     20    2497    3662    3656    4776    6946 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>bikes <span class="sc">%&gt;%</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="fu">sd</span>(riders_registered))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `sd(riders_registered)`
                    &lt;dbl&gt;
1                   1560.</code></pre>
</div>
</div>
</section>
<section id="exercise-3-explore-the-relationship-between-ridership-and-temperature-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3-explore-the-relationship-between-ridership-and-temperature-1">Exercise 3: Explore the relationship between ridership and temperature</h2>
<p>We’d like to understand how daily ridership among registered users relates with the temperature that it feels like that day (<code>temp_feel</code>).</p>
<ol type="a">
<li>Scatterplot (outcome and predictor are both quantitative)</li>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bikes, <span class="fu">aes</span>(<span class="at">x =</span> temp_feel, <span class="at">y =</span> riders_registered)) <span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_slr_formalization_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="a">
<li>If we only displayed the red line of best fit on the plot, we might miss the slight downward trend at the highest temperatures that we can see more clearly with the blue curve of best fit. A linear model is not appropriate if fit to the whole range of the data, but there does seem to be a linear relationship between ridership and temperature below 80 degrees Fahrenheit.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a red straight line of best fit and a blue curve of best fit</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bikes, <span class="fu">aes</span>(<span class="at">x =</span> temp_feel, <span class="at">y =</span> riders_registered)) <span class="sc">+</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_slr_formalization_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="exercise-4-filtering-our-data-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4-filtering-our-data-1">Exercise 4: Filtering our data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The %&gt;% is called a "pipe" and feeds what comes before it</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co"># into what comes after (bikes data is "fed into" the filter() function)</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>bikes_sub <span class="ot">&lt;-</span> bikes <span class="sc">%&gt;%</span> </span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(temp_feel <span class="sc">&lt;</span> <span class="dv">80</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercise-5-model-fitting-and-coefficient-interpretation-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5-model-fitting-and-coefficient-interpretation-1">Exercise 5: Model fitting and coefficient interpretation</h2>
<p>Let’s fit a simple linear regression model and examine the results. Step through code chunk slowly, and make note of new code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct and save the model as bike_mod</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># What's the purpose of "riders_registered ~ temp_feel"?</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># What's the purpose of "data = bikes_sub"?</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>bike_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(riders_registered <span class="sc">~</span> temp_feel, <span class="at">data =</span> bikes_sub)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A long summary of the model stored in bike_mod</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bike_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = riders_registered ~ temp_feel, data = bikes_sub)

Residuals:
    Min      1Q  Median      3Q     Max 
-3681.8  -928.3   -98.6   904.9  3496.7 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2486.412    421.379  -5.901 7.37e-09 ***
temp_feel      86.493      6.464  13.380  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1267 on 428 degrees of freedom
Multiple R-squared:  0.2949,    Adjusted R-squared:  0.2933 
F-statistic:   179 on 1 and 428 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A simplified model summary</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(bike_mod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) -2486.41180 421.379174 -5.900652 7.368345e-09
temp_feel      86.49251   6.464247 13.380135 2.349753e-34</code></pre>
</div>
</div>
<ol type="a">
<li><p>E[riders_registered | temp_feel] = -2486.41180 + 86.49251 * temp_feel</p></li>
<li><p><strong>Intercept interpretation:</strong> On days that feel like 0 degrees Fahrenheit, we can expect an average of -2486.41180 riders—a negative number of riders doesn’t make sense! This results because of <strong>extrapolation</strong>—0 degrees is so far below the minimum temperature in the data. We only have information on the relationship between ridership and temperature in the ~40-100 degree range and have no idea what that relationship looks like outside that range.</p></li>
<li><p><strong>Slope interpretation:</strong> Every 1 degree increase in feeling temperature is associated with an average of about 86 more riders.</p></li>
</ol>
</section>
<section id="exercise-6-predictions-and-residuals-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-6-predictions-and-residuals-1">Exercise 6: Predictions and residuals</h2>
<p>On August 17, 2012, the <code>temp_feel</code> was 53.816 degrees and there were 5665 riders. We can get data for this day using the <code>filter()</code> and <code>select()</code> <code>dplyr</code> functions. Note, but don’t worry about the syntax – we haven’t learned this yet:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>bikes_sub <span class="sc">%&gt;%</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(date <span class="sc">==</span> <span class="st">"2012-08-17"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(riders_registered, temp_feel) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  riders_registered temp_feel
              &lt;dbl&gt;     &lt;dbl&gt;
1              5665      53.8</code></pre>
</div>
</div>
<ol type="a">
<li><p><em>More</em> riders than expected – the point is far above the trend line</p></li>
<li><p>-2486.41180 + 86.49251 * 53.816 = 2168.269</p></li>
<li><p>We get the same result with <code>predict()</code>:</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What is the purpose of newdata = ___???</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(bike_mod, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">temp_feel =</span> <span class="fl">53.816</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
2168.269 </code></pre>
</div>
</div>
<ol start="4" type="a">
<li><p>residual = 5665 - 2168.269 = 3496.731. On August 17, 2012, there were 3496.731 more riders than would be expected from our model.</p></li>
<li><ul>
<li>Positive residuals are above the trend line—we under-estimate ridership.</li>
<li>Negative residuals are below the trend line—we over-estimate ridership.</li>
</ul></li>
<li><p>On an 85 degree day, we would predict 4865.452 riders. Even though we can compute this prediction, it’s not a good idea because of extrapolation–the data that we used to fit our model was filtered to days less than 80 degrees.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2486.41180</span> <span class="sc">+</span> <span class="fl">86.49251</span> <span class="sc">*</span> <span class="dv">85</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4865.452</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(bike_mod, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">temp_feel =</span> <span class="dv">85</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
4865.451 </code></pre>
</div>
</div>
</section>
<section id="exercise-7-changing-temperature-units-challenge-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-7-changing-temperature-units-challenge-1">Exercise 7: Changing temperature units (CHALLENGE)</h2>
<p>If we had measured temperature in degrees Celsius rather than degrees Fahrenheit, both the intercept and slope should change. The intercept would now represent 0 degrees Celsius (32 degrees Fahrenheit) and a one unit change in temperature is now 1 degree Celsius (1.8 degrees Fahrenheit).</p>
</section>
<section id="exercise-8-ridership-and-windspeed-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-8-ridership-and-windspeed-1">Exercise 8: Ridership and windspeed</h2>
<p>Let’s pull together everything that you’ve practiced in the preceding exercises to investigate the relationship between <code>riders_registered</code> and <code>windspeed</code>. Go back to using the <code>bikes</code> dataset (instead of <code>bikes_sub</code>) because we no longer need to only keep days less than 80 degrees.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct and interpret a visualization of this relationship</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Include a representation of the relationship trend</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bikes, <span class="fu">aes</span>(<span class="at">x =</span> windspeed, <span class="at">y =</span> riders_registered)) <span class="sc">+</span> </span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_slr_formalization_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use lm to construct a model of riders_registered vs windspeed</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Save this as bike_mod2</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>bike_mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(riders_registered <span class="sc">~</span> windspeed, <span class="at">data =</span> bikes)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a short summary of this model</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(bike_mod2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error   t value      Pr(&gt;|t|)
(Intercept) 4490.09761  149.65992 30.002005 2.023179e-129
windspeed    -65.34145   10.86299 -6.015053  2.844453e-09</code></pre>
</div>
</div>
<ol type="a">
<li><p>There’s a weak, negative relationship – ridership tends to be smaller on windier days.</p></li>
<li><p>E[riders_registered | windspeed] = 4490.09761 - 65.34145 windspeed</p></li>
<li><ul>
<li><strong>Intercept:</strong> On days with no wind, we’d expect around 4490 riders. (0 is a little below the minimum of the observed data, but not by much! So extrapolation in interpreting the intercept isn’t a huge concern.)</li>
<li><strong>Slope:</strong> Every 1mph increase in windspeed is associated with a ridership decrease of 65 riders on average.</li>
</ul></li>
<li><p>See the code below to predict ridership on August 17, 2012 and calculate the corresponding residual. Note that this residual is smaller than the residual from the temperature model (that residual was 3496.731). This indicates that August 17 was more of an outlier in ridership given the temperature than the windspeed.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>bikes <span class="sc">%&gt;%</span> </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(date <span class="sc">==</span> <span class="st">"2012-08-17"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(riders_registered, windspeed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  riders_registered windspeed
              &lt;dbl&gt;     &lt;dbl&gt;
1              5665      15.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prediction</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fl">4490.09761</span> <span class="sc">-</span> <span class="fl">65.34145</span> <span class="sc">*</span> <span class="fl">15.50072</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3477.258</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># residual </span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="dv">5665</span> <span class="sc">-</span> <span class="fl">3477.258</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2187.742</code></pre>
</div>
</div>
</section>
<section id="exercise-9-data-drills-filter-select-summarize-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-9-data-drills-filter-select-summarize-1">Exercise 9: Data drills (<code>filter</code>, <code>select</code>, <code>summarize</code>)</h2>
<p>This exercise is designed to help you keep building your <code>dplyr</code> skills. These skills are important to data cleaning and digging, which in turn is important to really making meaning of our data. We’ll work with a simpler set of 10 data points:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="ot">&lt;-</span> bikes <span class="sc">%&gt;%</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(date, temp_feel, humidity, riders_registered, day_of_week) <span class="sc">%&gt;%</span> </span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="verb-1-summarize-1" class="level3">
<h3 class="anchored" data-anchor-id="verb-1-summarize-1">Verb 1: <code>summarize</code></h3>
<p><code>summarize()</code> calculates numerical summaries of variables (columns).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="fu">mean</span>(temp_feel), <span class="fu">mean</span>(humidity))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  `mean(temp_feel)` `mean(humidity)`
              &lt;dbl&gt;            &lt;dbl&gt;
1              52.0            0.544</code></pre>
</div>
</div>
</section>
<section id="verb-2-select-1" class="level3">
<h3 class="anchored" data-anchor-id="verb-2-select-1">Verb 2: <code>select</code></h3>
<p><code>select()</code> selects variables (columns).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(date, temp_feel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   date       temp_feel
   &lt;date&gt;         &lt;dbl&gt;
 1 2011-01-01      64.7
 2 2011-01-02      63.8
 3 2011-01-03      49.0
 4 2011-01-04      51.1
 5 2011-01-05      52.6
 6 2011-01-06      53.0
 7 2011-01-07      50.8
 8 2011-01-08      46.6
 9 2011-01-09      42.5
10 2011-01-10      45.6</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>date, <span class="sc">-</span>temp_feel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   humidity riders_registered day_of_week
      &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;      
 1    0.806               654 Sat        
 2    0.696               670 Sun        
 3    0.437              1229 Mon        
 4    0.590              1454 Tue        
 5    0.437              1518 Wed        
 6    0.518              1518 Thu        
 7    0.499              1362 Fri        
 8    0.536               891 Sat        
 9    0.434               768 Sun        
10    0.483              1280 Mon        </code></pre>
</div>
</div>
</section>
<section id="verb-3-filter-1" class="level3">
<h3 class="anchored" data-anchor-id="verb-3-filter-1">Verb 3: <code>filter</code></h3>
<p><code>filter()</code> keeps only days (rows) that meet the given condition(s).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(riders_registered <span class="sc">&gt;</span> <span class="dv">850</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 5
  date       temp_feel humidity riders_registered day_of_week
  &lt;date&gt;         &lt;dbl&gt;    &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;      
1 2011-01-03      49.0    0.437              1229 Mon        
2 2011-01-04      51.1    0.590              1454 Tue        
3 2011-01-05      52.6    0.437              1518 Wed        
4 2011-01-06      53.0    0.518              1518 Thu        
5 2011-01-07      50.8    0.499              1362 Fri        
6 2011-01-08      46.6    0.536               891 Sat        
7 2011-01-10      45.6    0.483              1280 Mon        </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(day_of_week <span class="sc">==</span> <span class="st">"Sat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  date       temp_feel humidity riders_registered day_of_week
  &lt;date&gt;         &lt;dbl&gt;    &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;      
1 2011-01-01      64.7    0.806               654 Sat        
2 2011-01-08      46.6    0.536               891 Sat        </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(riders_registered <span class="sc">&gt;</span> <span class="dv">850</span>, day_of_week <span class="sc">==</span> <span class="st">"Sat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  date       temp_feel humidity riders_registered day_of_week
  &lt;date&gt;         &lt;dbl&gt;    &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;      
1 2011-01-08      46.6    0.536               891 Sat        </code></pre>
</div>
</div>
</section>
</section>
<section id="exercise-10-your-turn-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-10-your-turn-1">Exercise 10: Your turn</h2>
<p>Use <code>dplyr</code> verbs to complete each task below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only information about the humidity and day of week</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(humidity, day_of_week)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   humidity day_of_week
      &lt;dbl&gt; &lt;chr&gt;      
 1    0.806 Sat        
 2    0.696 Sun        
 3    0.437 Mon        
 4    0.590 Tue        
 5    0.437 Wed        
 6    0.518 Thu        
 7    0.499 Fri        
 8    0.536 Sat        
 9    0.434 Sun        
10    0.483 Mon        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only information about the humidity and day of week using a different approach</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>date, <span class="sc">-</span>temp_feel, <span class="sc">-</span>riders_registered)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   humidity day_of_week
      &lt;dbl&gt; &lt;chr&gt;      
 1    0.806 Sat        
 2    0.696 Sun        
 3    0.437 Mon        
 4    0.590 Tue        
 5    0.437 Wed        
 6    0.518 Thu        
 7    0.499 Fri        
 8    0.536 Sat        
 9    0.434 Sun        
10    0.483 Mon        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only information for Sundays</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(day_of_week <span class="sc">==</span> <span class="st">"Sun"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  date       temp_feel humidity riders_registered day_of_week
  &lt;date&gt;         &lt;dbl&gt;    &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;      
1 2011-01-02      63.8    0.696               670 Sun        
2 2011-01-09      42.5    0.434               768 Sun        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only information for Sundays with temperatures below 50</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(day_of_week <span class="sc">==</span> <span class="st">"Sun"</span>, temp_feel <span class="sc">&lt;</span> <span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  date       temp_feel humidity riders_registered day_of_week
  &lt;date&gt;         &lt;dbl&gt;    &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;      
1 2011-01-09      42.5    0.434               768 Sun        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the maximum and minimum temperatures</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>new_bikes <span class="sc">%&gt;%</span> </span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="fu">min</span>(temp_feel), <span class="fu">max</span>(temp_feel))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  `min(temp_feel)` `max(temp_feel)`
             &lt;dbl&gt;            &lt;dbl&gt;
1             42.5             64.7</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Leslie Myint, 2024<br> All content licensed under <img src="https://static.thenounproject.com/png/70967-200.png" height="20"> (<a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>)</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Site built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>