<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Multiple logistic regression – STAT 155</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">STAT 155</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-activities" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Activities</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-activities">    
        <li>
    <a class="dropdown-item" href="../activities/01_foundations_welcome.html">
 <span class="dropdown-text">Data Fundamentals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/02_foundations_univariate.html">
 <span class="dropdown-text">Univariate visualization and summaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/03_slr_introduction.html">
 <span class="dropdown-text">Simple linear regression: Visualization and Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/04_slr_formalization.html">
 <span class="dropdown-text">Simple linear regression: formalizing concepts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/05_slr_model_eval.html">
 <span class="dropdown-text">Simple linear regression: model evaluation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/06_slr_transformations.html">
 <span class="dropdown-text">Simple linear regression: Transformations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/07_slr_cat_predictor.html">
 <span class="dropdown-text">Simple linear regression: categorical predictor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/08_mlr_intro.html">
 <span class="dropdown-text">Introduction to multiple regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/09_mlr_principles.html">
 <span class="dropdown-text">Multiple regression principles</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/10_mlr_confounding.html">
 <span class="dropdown-text">Confounding variables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/11_mlr_interaction_explore.html">
 <span class="dropdown-text">Multiple linear regression: exploring interaction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/12_mlr_interaction_practice.html">
 <span class="dropdown-text">Multiple linear regression: interaction terms practice</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/13_mlr_model_building_1.html">
 <span class="dropdown-text">Multiple linear regression: model building (part 1)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/14_mlr_model_building_2.html">
 <span class="dropdown-text">Multiple linear regression: model building (part 2)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/15_prob_odds.html">
 <span class="dropdown-text">Probability and Odds</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/16_logistic_univariate.html">
 <span class="dropdown-text">Simple logistic regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/17_logistic_multivariate_evaluation.html">
 <span class="dropdown-text">Multiple logistic regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../activities/18_sampling_normal.html">
 <span class="dropdown-text">The Normal model &amp; sampling variation</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practice-problems" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practice Problems</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practice-problems">    
        <li>
    <a class="dropdown-item" href="../assignments/pp1.html">
 <span class="dropdown-text">Practice Problems 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../assignments/pp2.html">
 <span class="dropdown-text">Practice Problems 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../assignments/pp3.html">
 <span class="dropdown-text">Practice Problems 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../assignments/pp4.html">
 <span class="dropdown-text">Practice Problems 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../assignments/pp5.html">
 <span class="dropdown-text">Practice Problems 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../project.html"> 
<span class="menu-text">Project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../r_resources.html"> 
<span class="menu-text">R Resources</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#notes" id="toc-notes" class="nav-link active" data-scroll-target="#notes">Notes</a>
  <ul class="collapse">
  <li><a href="#learning-goals" id="toc-learning-goals" class="nav-link" data-scroll-target="#learning-goals">Learning goals</a></li>
  <li><a href="#readings-and-videos" id="toc-readings-and-videos" class="nav-link" data-scroll-target="#readings-and-videos">Readings and videos</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
  <li><a href="#exercise-1-graphical-and-numerical-summaries" id="toc-exercise-1-graphical-and-numerical-summaries" class="nav-link" data-scroll-target="#exercise-1-graphical-and-numerical-summaries">Exercise 1: Graphical and numerical summaries</a></li>
  <li><a href="#exercise-2-logistic-regression-modeling" id="toc-exercise-2-logistic-regression-modeling" class="nav-link" data-scroll-target="#exercise-2-logistic-regression-modeling">Exercise 2: Logistic regression modeling</a></li>
  <li><a href="#exercise-3-interaction-terms" id="toc-exercise-3-interaction-terms" class="nav-link" data-scroll-target="#exercise-3-interaction-terms">Exercise 3: Interaction terms</a></li>
  <li><a href="#exercise-4-prediction" id="toc-exercise-4-prediction" class="nav-link" data-scroll-target="#exercise-4-prediction">Exercise 4: Prediction</a></li>
  <li><a href="#exercise-5-evaluating-logistic-models-with-plots" id="toc-exercise-5-evaluating-logistic-models-with-plots" class="nav-link" data-scroll-target="#exercise-5-evaluating-logistic-models-with-plots">Exercise 5: Evaluating logistic models with plots</a></li>
  <li><a href="#exercise-6-evaluating-logistic-models-with-evaluation-metrics" id="toc-exercise-6-evaluating-logistic-models-with-evaluation-metrics" class="nav-link" data-scroll-target="#exercise-6-evaluating-logistic-models-with-evaluation-metrics">Exercise 6: Evaluating logistic models with evaluation metrics</a></li>
  <li><a href="#reflection" id="toc-reflection" class="nav-link" data-scroll-target="#reflection">Reflection</a></li>
  <li><a href="#render-your-work" id="toc-render-your-work" class="nav-link" data-scroll-target="#render-your-work">Render your work</a></li>
  </ul></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions">Solutions</a>
  <ul class="collapse">
  <li><a href="#exercise-1-graphical-and-numerical-summaries-1" id="toc-exercise-1-graphical-and-numerical-summaries-1" class="nav-link" data-scroll-target="#exercise-1-graphical-and-numerical-summaries-1">Exercise 1: Graphical and numerical summaries</a></li>
  <li><a href="#exercise-2-logistic-regression-modeling-1" id="toc-exercise-2-logistic-regression-modeling-1" class="nav-link" data-scroll-target="#exercise-2-logistic-regression-modeling-1">Exercise 2: Logistic regression modeling</a></li>
  <li><a href="#exercise-3-interaction-terms-1" id="toc-exercise-3-interaction-terms-1" class="nav-link" data-scroll-target="#exercise-3-interaction-terms-1">Exercise 3: Interaction terms</a></li>
  <li><a href="#exercise-4-prediction-1" id="toc-exercise-4-prediction-1" class="nav-link" data-scroll-target="#exercise-4-prediction-1">Exercise 4: Prediction</a></li>
  <li><a href="#exercise-5-evaluating-logistic-models-with-plots-1" id="toc-exercise-5-evaluating-logistic-models-with-plots-1" class="nav-link" data-scroll-target="#exercise-5-evaluating-logistic-models-with-plots-1">Exercise 5: Evaluating logistic models with plots</a></li>
  <li><a href="#exercise-6-evaluating-logistic-models-with-evaluation-metrics-1" id="toc-exercise-6-evaluating-logistic-models-with-evaluation-metrics-1" class="nav-link" data-scroll-target="#exercise-6-evaluating-logistic-models-with-evaluation-metrics-1">Exercise 6: Evaluating logistic models with evaluation metrics</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multiple logistic regression</h1>
<p class="subtitle lead">Notes and in-class exercises</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="notes" class="level1">
<h1>Notes</h1>
<ul>
<li>You can download a template file to work with <a href="../activity_templates/17_logistic_multivariate_evaluation.qmd">here</a>.</li>
<li><strong>File organization:</strong> Save this file in the “Activities” subfolder of your “STAT155” folder.</li>
</ul>
<section id="learning-goals" class="level2">
<h2 class="anchored" data-anchor-id="learning-goals">Learning goals</h2>
<p>By the end of this lesson, you should be able to:</p>
<ul>
<li>Construct multiple logistic regression models in R</li>
<li>Interpret coefficients in multiple logistic regression models</li>
<li>Use multiple logistic regression models to make predictions</li>
<li>Evaluate the quality of logistic regression models by using predicted probability boxplots and by computing and interpreting accuracy, sensitivity, specificity, false positive rate, and false negative rate</li>
</ul>
</section>
<section id="readings-and-videos" class="level2">
<h2 class="anchored" data-anchor-id="readings-and-videos">Readings and videos</h2>
<p>Before class, you should have read:</p>
<ul>
<li>Reading: Section 4.4 in the <a href="https://mac-stat.github.io/Stat155Notes/">STAT 155 Notes</a></li>
</ul>
</section>
</section>
<section id="exercises" class="level1">
<h1>Exercises</h1>
<p><strong>Context:</strong> In this activity, we’ll look at data from an experiment conducted in 2001-2002 that investigated the influence of race and gender on job applications. The researchers created realistic-looking resumes and then randomly assigned a name to the resume that “would communicate the applicant’s gender and race” (e.g., they they assumed the name Emily would generally be interpreted as a white woman, whereas the name Jamal would generally be interpreted as a black man). They then submitted these resumes to job postings in Boston and Chicago and waited to see if the applicant got a call back from the job posting.</p>
<p>You can find a full description of the variables in this dataset <a href="https://www.openintro.org/data/index.php?data=resume">here</a>. Today, we’ll focus on the following variables:</p>
<ul>
<li><code>received_callback</code>: indicator that the resume got a call back from the job posting</li>
<li><code>gender</code>: inferred binary gender associated with the first name on the resume</li>
<li><code>race</code>: inferred race associated with the first name on the resume</li>
</ul>
<p>Our research question is: <strong>does an applicant’s inferred gender and race have an effect on the chance that they receive a callback after submitting their resume for an open job posting?</strong></p>
<p>You’ll need to run <code>install.packages("broom")</code> in the Console first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggmosaic)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>resume <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://mac-stat.github.io/data/resume.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 4870 Columns: 30</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (10): job_city, job_industry, job_type, job_ownership, job_req_min_exper...
dbl (20): job_ad_id, job_fed_contractor, job_equal_opp_employer, job_req_any...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<section id="exercise-1-graphical-and-numerical-summaries" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1-graphical-and-numerical-summaries">Exercise 1: Graphical and numerical summaries</h2>
<p>Our research question involves three categorical variables: <code>received_callback</code> (1 = yes, 0 = no), <code>gender</code> (f = female, m = male), and <code>race</code> (Black, White). Let’s start by creating a mosaic plot to visually compare inferred binary gender and callbacks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create mosaic plot of callback vs gender</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resume) <span class="sc">+</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(gender), <span class="at">fill =</span> received_callback)) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_manual</span>(<span class="st">"Received Callback? </span><span class="sc">\n</span><span class="st">(1 = yes, 0 = no)"</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"steelblue"</span>)) <span class="sc">+</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Inferred Binary Gender (f = female, m = male)"</span>, <span class="at">y =</span> <span class="st">"Received Callback? (1 = yes, 0 = no)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this activity, we’re also interested in looking at the relationship between inferred race and callbacks. One way we can add a third variable to a plot is to use the <code>facet_grid</code> function, particularly when that third variable is categorical. Let’s try that now:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create mosaic plot of callback vs gender and race</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resume) <span class="sc">+</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(gender), <span class="at">fill =</span> received_callback)) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_grid</span>(. <span class="sc">~</span> race) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_manual</span>(<span class="st">"Received Callback? </span><span class="sc">\n</span><span class="st">(1 = yes, 0 = no)"</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"steelblue"</span>)) <span class="sc">+</span> </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Inferred Binary Gender (f = female, m = male)"</span>, <span class="at">y =</span> <span class="st">"Received Callback? (1 = yes, 0 = no)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here’s another way of looking at the relationship between these three variables, switching the placement of <code>gender</code> and <code>race</code> in the mosaic plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create mosaic plot of callback vs gender and race</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resume) <span class="sc">+</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(received_callback, race), <span class="at">fill =</span> received_callback)) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_grid</span>(. <span class="sc">~</span> gender) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_manual</span>(<span class="st">"Received Callback? </span><span class="sc">\n</span><span class="st">(1 = yes, 0 = no)"</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"steelblue"</span>)) <span class="sc">+</span> </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Inferred Race"</span>, <span class="at">y =</span> <span class="st">"Received Callback? (1 = yes, 0 = no)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When we are comparing three categorical variables, a useful numerical summary is to calculate relative frequencies/proportions of cases falling into each category of the outcome variable, conditional on which categories of the explanatory variables they fall into. Run this code chunk to calculate the conditional proportion of resumes that did nor did not receive a callback, given the inferred gender and race of the applicant:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># corresponding numerical summaries</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>resume <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(race, gender) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(received_callback) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(race, gender) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">condprop =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Write a short description that summarizes the information you gain from these visualizations and numerical summaries. Write this summary using good sentences that tell a story and do not resemble a checklist. Don’t forget to consider the context of the data, and make sure that your summary addresses our research question: <em>does an applicant’s inferred gender or race have an effect on the chance that they receive a callback?</em></p>
</section>
<section id="exercise-2-logistic-regression-modeling" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2-logistic-regression-modeling">Exercise 2: Logistic regression modeling</h2>
<p>Next, we’ll fit a logistic regression model to these data, modeling the <em>log odds</em> of receiving a callback as a function of the applicant’s inferred gender and race:</p>
<p><span class="math display">\[\log(Odds[ReceivedCallback = 1 \mid gender, race]) = \beta_0 + \beta_1 genderm + \beta_2 racewhite\]</span></p>
<p>Fill in the blanks in the code below to fit this logistic regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit logistic model and save it as object called "mod1"</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(received_callback <span class="sc">~</span> gender <span class="sc">+</span> race, <span class="at">data =</span> ___, <span class="at">family =</span> ___)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, run the code chunk below to get the coefficient estimates and exponentiated estimates, presented in a nicely formatted table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print out tidy summary of mod, focusing on estimates &amp; exponentiated estimates</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mod1) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(term, estimate) <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">estimate_exp =</span> <span class="fu">exp</span>(estimate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Write an interpretation of each of the exponentiated coefficients in your logistic regression model.</p>
</section>
<section id="exercise-3-interaction-terms" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3-interaction-terms">Exercise 3: Interaction terms</h2>
<ol type="a">
<li><p>Do you think it would make sense to add an interaction term (between gender and race) to our logistic regression model? Why/why not?</p></li>
<li><p>Let’s try adding an interaction between gender and race. Update the code below to fit this new interaction model.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit logistic model and save it as object called "mod2"</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(received_callback <span class="sc">~</span> ___, <span class="at">data =</span> resume, <span class="at">family =</span> ___)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, run the code chunk below to get the coefficient estimates and exponentiated estimates for this interaction model, presented in a nicely formatted table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print out tidy summary of mod, focusing on estimates &amp; exponentiated estimates</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mod2) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(term, estimate) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">estimate_exp =</span> <span class="fu">exp</span>(estimate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="a">
<li>(CHALLENGE) Write out the logistic regression model formula separately for males and for females. Based on this how would we interpret the exponentiated coefficients in this model?</li>
</ol>
</section>
<section id="exercise-4-prediction" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4-prediction">Exercise 4: Prediction</h2>
<p>We can use our models to predict whether or not a resume will receive a call back based on the inferred gender and race of the applicant. Run the code below to use the <code>predict()</code> function to predict the probability of getting a call back for four job applicants: a person inferred to be a black female, a person inferred to be black male, a person inferred to be a white female, and a person inferred to be a white male.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set up data frame with people we want to predict for</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>predict_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">gender =</span> <span class="fu">c</span>(<span class="st">"f"</span>, <span class="st">"m"</span>, <span class="st">"f"</span>, <span class="st">"m"</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">race =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"black"</span>, <span class="st">"white"</span>, <span class="st">"white"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predict_data)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># prediction based on model without interaction</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>mod1 <span class="sc">%&gt;%</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">predict</span>(<span class="at">newdata =</span> predict_data, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="co"># prediction based on model with interaction</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>mod2 <span class="sc">%&gt;%</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">predict</span>(<span class="at">newdata =</span> predict_data, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Report and compare the predictions we get from <code>predict()</code>. Do they make sense to you based on your understanding of the data? Combine insights from visualizations and modeling to write a few sentences summarizing findings for our research question: <em>does an applicant’s inferred gender and race have an effect on the chance that they receive a callback after submitting their resume for an open job posting?</em></p>
</section>
<section id="exercise-5-evaluating-logistic-models-with-plots" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5-evaluating-logistic-models-with-plots">Exercise 5: Evaluating logistic models with plots</h2>
<p>We’ll fit one more model that adds on to the interaction model to also include years of college, years of work experience, and resume quality. The <code>augment()</code> code takes our fitted models and stores the predicted probabilities in a variable called <code>.fitted</code>. Then we use boxplots to show the predicted probabilities of receiving a callback in those who actually did and did not receive a callback.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(received_callback <span class="sc">~</span> gender<span class="sc">*</span>race <span class="sc">+</span> years_college <span class="sc">+</span> years_experience <span class="sc">+</span> resume_quality, <span class="at">data =</span> resume, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>mod1_output <span class="ot">&lt;-</span> <span class="fu">augment</span>(mod1, <span class="at">type.predict =</span> <span class="st">"response"</span>) <span class="co"># Store predicted probabilities in a variable called .fitted</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>mod2_output <span class="ot">&lt;-</span> <span class="fu">augment</span>(mod2, <span class="at">type.predict =</span> <span class="st">"response"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>mod3_output <span class="ot">&lt;-</span> <span class="fu">augment</span>(mod3, <span class="at">type.predict =</span> <span class="st">"response"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod1_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod2_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod3_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="a">
<li><p>Summarize what you learn about the ability of the 3 models to differentiate those who actually did and did not receive a callback. What model seems best, and why?</p></li>
<li><p>If you had to draw a horizontal line across each of the boxplots that vertically separates the left and right boxplots well, where would you place them?</p></li>
</ol>
</section>
<section id="exercise-6-evaluating-logistic-models-with-evaluation-metrics" class="level2">
<h2 class="anchored" data-anchor-id="exercise-6-evaluating-logistic-models-with-evaluation-metrics">Exercise 6: Evaluating logistic models with evaluation metrics</h2>
<p>Sometimes we may need to go beyond the predicted probabilities from our model and try to classify individuals into one of the two binary outcomes (received or did not receive a callback). How high of a predicted probability would we need from our model in order to be convinced that the person actually got a callback? This is the idea behind the horizontal lines that we drew in the previous exercise.</p>
<p>Let’s explore using a probability threshold of 0.08 (8%) to make a binary prediction for each case:</p>
<ul>
<li>If a model’s predicted probability of getting a callback is greater than or equal to 8.5%, we’ll predict they got a callback.</li>
<li>If the predicted probability is below 8%, we’ll predict they didn’t get a callback.</li>
</ul>
<p>We can visualize this threshold on our predicted probability boxplots:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod1_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.08</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod2_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.08</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod3_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.08</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we can use our threshold to classify each person in our dataset based on their predicted probability of getting a callback: we’ll predict that everyone with a predicted probability higher than our threshold got a callback, and otherwise they did not. Then, we’ll compare our model’s prediction to the true outcome (whether or not they actually did get a callback).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get binary predictions for mod1 and compare to truth</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> <span class="fl">0.08</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>mod1_output <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">predictCallback =</span> .fitted <span class="sc">&gt;=</span> threshold) <span class="sc">%&gt;%</span> <span class="do">## predict callback if probability greater than or equal to threshold</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(received_callback, predictCallback) <span class="do">## compare actual and predicted callbacks</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>mod2_output <span class="sc">%&gt;%</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">predictCallback =</span> .fitted <span class="sc">&gt;=</span> threshold) <span class="sc">%&gt;%</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(received_callback, predictCallback)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>mod3_output <span class="sc">%&gt;%</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">predictCallback =</span> .fitted <span class="sc">&gt;=</span> threshold) <span class="sc">%&gt;%</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(received_callback, predictCallback)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can use the <code>count()</code> output to fill create contingency tables of the results. (These tables are also called <strong>confusion matrices</strong>.)</p>
<ol type="a">
<li>Fill in the confusion matrix for Model 3.</li>
</ol>
<blockquote class="blockquote">
<p>Models 1 and 2: (Both models result in the same confusion matrix.)</p>
</blockquote>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Predict callback</th>
<th style="text-align: center;">Predict no callback</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Actually got callback</td>
<td style="text-align: center;">235</td>
<td style="text-align: center;">157</td>
<td style="text-align: center;">392</td>
</tr>
<tr class="even">
<td>Actually did not</td>
<td style="text-align: center;">2200</td>
<td style="text-align: center;">2278</td>
<td style="text-align: center;">4478</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: center;">2435</td>
<td style="text-align: center;">2435</td>
<td style="text-align: center;">4870</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>Model 3:</p>
</blockquote>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Predict callback</th>
<th style="text-align: center;">Predict no callback</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Actually got callback</td>
<td style="text-align: center;">____</td>
<td style="text-align: center;">____</td>
<td style="text-align: center;">____</td>
</tr>
<tr class="even">
<td>Actually did not</td>
<td style="text-align: center;">____</td>
<td style="text-align: center;">____</td>
<td style="text-align: center;">____</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: center;">____</td>
<td style="text-align: center;">____</td>
<td style="text-align: center;">____</td>
</tr>
</tbody>
</table>
<ol start="2" type="a">
<li>Now compute the following evaluation metrics for the models:</li>
</ol>
<p>Models 1 and 2:</p>
<ul>
<li>Accuracy: P(Predict Y Correctly)</li>
<li>Sensitivity: P(Predict Y = 1 | Actual Y = 1)</li>
<li>Specificity: P(Predict Y = 0 | Actual Y = 0)</li>
<li>False negative rate: P(Predict Y = 0 | Actual Y = 1)</li>
<li>False positive rate: P(Predict Y = 1 | Actual Y = 0)</li>
</ul>
<p>Model 3:</p>
<ul>
<li>Accuracy: P(Predict Y Correctly)</li>
<li>Sensitivity: P(Predict Y = 1 | Actual Y = 1)</li>
<li>Specificity: P(Predict Y = 0 | Actual Y = 0)</li>
<li>False negative rate: P(Predict Y = 0 | Actual Y = 1)</li>
<li>False positive rate: P(Predict Y = 1 | Actual Y = 0)</li>
</ul>
<ol start="3" type="a">
<li>Imagine that we are a career center on a college campus and we want to use this model to help students that are looking for jobs. Consider the consequences of incorrectly predicting whether or not an individual will get a callback. What are the consequences of a false negative? What about a false positive? Which one is worse?</li>
</ol>
</section>
<section id="reflection" class="level2">
<h2 class="anchored" data-anchor-id="reflection">Reflection</h2>
<p>What are some similarities and differences between how we interpret and evaluate linear and logistic regression models?</p>
<blockquote class="blockquote">
<p><strong>Response:</strong> Put your response here.</p>
</blockquote>
</section>
<section id="render-your-work" class="level2">
<h2 class="anchored" data-anchor-id="render-your-work">Render your work</h2>
<ul>
<li>Click the “Render” button in the menu bar for this pane (blue arrow pointing right). This will create an HTML file containing all of the directions, code, and responses from this activity. A preview of the HTML will appear in the browser.</li>
<li>Scroll through and inspect the document to check that your work translated to the HTML format correctly.</li>
<li>Close the browser tab.</li>
<li>Go to the “Background Jobs” pane in RStudio and click the Stop button to end the rendering process.</li>
<li>Navigate to your “Activities” subfolder within your “STAT155” folder and locate the HTML file. You can open it again in your browser to double check.</li>
</ul>
<p><br><br><br><br><br><br></p>
</section>
</section>
<section id="solutions" class="level1">
<h1>Solutions</h1>
<section id="exercise-1-graphical-and-numerical-summaries-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1-graphical-and-numerical-summaries-1">Exercise 1: Graphical and numerical summaries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resume) <span class="sc">+</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(gender), <span class="at">fill =</span> received_callback)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_manual</span>(<span class="st">"Received Callback? </span><span class="sc">\n</span><span class="st">(1 = yes, 0 = no)"</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"steelblue"</span>)) <span class="sc">+</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Inferred Binary Gender (f = female, m = male)"</span>, <span class="at">y =</span> <span class="st">"Received Callback? (1 = yes, 0 = no)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `scale_name` argument of `continuous_scale()` is deprecated as of ggplot2
3.5.0.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `trans` argument of `continuous_scale()` is deprecated as of ggplot2 3.5.0.
ℹ Please use the `transform` argument instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `unite_()` was deprecated in tidyr 1.2.0.
ℹ Please use `unite()` instead.
ℹ The deprecated feature was likely used in the ggmosaic package.
  Please report the issue at &lt;https://github.com/haleyjeppson/ggmosaic&gt;.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="17_logistic_multivariate_evaluation_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resume) <span class="sc">+</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(gender), <span class="at">fill =</span> received_callback)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_grid</span>(. <span class="sc">~</span> race) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_manual</span>(<span class="st">"Received Callback? </span><span class="sc">\n</span><span class="st">(1 = yes, 0 = no)"</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"steelblue"</span>)) <span class="sc">+</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Inferred Binary Gender (f = female, m = male)"</span>, <span class="at">y =</span> <span class="st">"Received Callback? (1 = yes, 0 = no)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="17_logistic_multivariate_evaluation_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resume) <span class="sc">+</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(received_callback, race), <span class="at">fill =</span> received_callback)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_grid</span>(. <span class="sc">~</span> gender) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_manual</span>(<span class="st">"Received Callback? </span><span class="sc">\n</span><span class="st">(1 = yes, 0 = no)"</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"steelblue"</span>)) <span class="sc">+</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Inferred Race"</span>, <span class="at">y =</span> <span class="st">"Received Callback? (1 = yes, 0 = no)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="17_logistic_multivariate_evaluation_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>resume <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(race, gender) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(received_callback) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(race, gender) <span class="sc">%&gt;%</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">condprop =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
# Groups:   race, gender [4]
  race  gender received_callback     n condprop
  &lt;chr&gt; &lt;chr&gt;              &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;
1 black f                      0  1761   0.934 
2 black f                      1   125   0.0663
3 black m                      0   517   0.942 
4 black m                      1    32   0.0583
5 white f                      0  1676   0.901 
6 white f                      1   184   0.0989
7 white m                      0   524   0.911 
8 white m                      1    51   0.0887</code></pre>
</div>
</div>
<p>Overall, a small proportion of applicants received a callback, with those who were inferred to be black males being least likely to get a callback (5.8%) and those inferred to be white females being most likely to get a callback (9.9%). In general, job applicants whose race was inferred to be white were more likely to receive a callback than those whose race was inferred to be black, regardless of their inferred gender. On the other hand, inferred gender does not seem to have as much of an effect on the chance of receiving a callback, with perhaps just a slight advantage for females.</p>
</section>
<section id="exercise-2-logistic-regression-modeling-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2-logistic-regression-modeling-1">Exercise 2: Logistic regression modeling</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(received_callback <span class="sc">~</span> gender <span class="sc">+</span> race, <span class="at">data =</span> resume, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mod1) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(term, estimate) <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">estimate_exp =</span> <span class="fu">exp</span>(estimate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  term        estimate estimate_exp
  &lt;chr&gt;          &lt;dbl&gt;        &lt;dbl&gt;
1 (Intercept)   -2.65        0.0708
2 genderm       -0.127       0.881 
3 racewhite      0.440       1.55  </code></pre>
</div>
</div>
<ul>
<li>exp(Intercept): We estimate the odds of getting a callback among those inferred to be black females is only 0.07, meaning that the chance of getting a callback is 0.07 times as large as the chance of not getting a callback (or, inversely, the chance of <em>not</em> getting a callback is 1/0.07 = 14.29) times greater than the chance of getting a callback).</li>
<li>exp(genderm): Comparing applicants of the same inferred race, we estimate that those inferred to be male have an odds of getting a callback that is 0.88 times as high as (or, equivalently, 12% lower than) the odds of getting a callback for those inferred to be female.</li>
<li>exp(racewhite): We estimate that the odds of getting a callback are 1.55 times higher for applicants whose race was inferred to be white as compared to those who were inferred to be black but the same gender.</li>
</ul>
</section>
<section id="exercise-3-interaction-terms-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3-interaction-terms-1">Exercise 3: Interaction terms</h2>
<ol type="a">
<li><p>Including an interaction term in our model would allow us to investigate whether the effect of race on getting a callback depends on your gender or, vice versa, if the effect of gender on getting a callback depends on a race. In other words, we could ask questions like: is there more of a discrepancy in callbacks between black and white males than there is among black and white females? Is there more of a discrepancy in callbacks between male and female blacks than there is among male and female whites?</p></li>
<li><p>Let’s try adding an interaction between gender and race. Update the code below to fit this new interaction model.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(received_callback <span class="sc">~</span> gender <span class="sc">*</span> race, <span class="at">data =</span> resume, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mod2) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(term, estimate) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">estimate_exp =</span> <span class="fu">exp</span>(estimate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  term              estimate estimate_exp
  &lt;chr&gt;                &lt;dbl&gt;        &lt;dbl&gt;
1 (Intercept)        -2.65         0.0710
2 genderm            -0.137        0.872 
3 racewhite           0.436        1.55  
4 genderm:racewhite   0.0165       1.02  </code></pre>
</div>
</div>
<ol start="3" type="a">
<li>Overall logistic regression model formula in terms of beta coefficients:</li>
</ol>
<p><span class="math display">\[\log(Odds[ReceivedCallback = 1 \mid gender, race]) = \beta_0 + \beta_1 genderm + \beta_2 racewhite + \beta_3 genderm \times racewhite\]</span></p>
<p>The model formula for males:</p>
<p><span class="math display">\[\log(Odds[ReceivedCallback = 1 \mid gender=m, race]) = (\beta_0 + \beta_1) + (\beta_2 + \beta_3) racewhite\]</span></p>
<p>The model formula for females:</p>
<p><span class="math display">\[\log(Odds[ReceivedCallback = 1 \mid gender=f, race]) = \beta_0 + \beta_2 racewhite\]</span> Focusing first on the female model formula, we can see that this is a simple logistic regression model.</p>
<ul>
<li>exp(beta0): Odds of callback for black females</li>
<li>exp(beta2): This is the odds ratio for race among females. That is, white females have exp(beta2) times the odds of callback than black females.</li>
</ul>
<p>Then focusing on the male model formula, we can see that this is also a simple logistic regression model.</p>
<ul>
<li>exp(beta0+beta1): Odds of callback for black males</li>
<li>exp(beta2+beta3): This is the odds ratio for race among males. White males have exp(beta2+beta3) times the odds of callback than black males.</li>
</ul>
<p>Comparing the male to the female model formula, we have:</p>
<ul>
<li>exp(beta1): Black males have exp(beta1) times the odds of a callback than black females</li>
<li>exp(beta3): This tells us how many times higher the odds ratio for race is in males as compared to females.</li>
</ul>
</section>
<section id="exercise-4-prediction-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4-prediction-1">Exercise 4: Prediction</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set up data frame with people we want to predict for</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>predict_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">gender =</span> <span class="fu">c</span>(<span class="st">"f"</span>, <span class="st">"m"</span>, <span class="st">"f"</span>, <span class="st">"m"</span>),</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">race =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"black"</span>, <span class="st">"white"</span>, <span class="st">"white"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predict_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  gender  race
1      f black
2      m black
3      f white
4      m white</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prediction based on model without interaction</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>mod1 <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">predict</span>(<span class="at">newdata =</span> predict_data, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4 
0.06615111 0.05872314 0.09905323 0.08828000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prediction based on model with interaction</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>mod2 <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">predict</span>(<span class="at">newdata =</span> predict_data, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4 
0.06627784 0.05828780 0.09892473 0.08869565 </code></pre>
</div>
</div>
<p>The predicted probabilities from our logistic regression models show that we estimate those inferred to be black males have the lowest chance of receiving a callback (5.87% based on <code>mod1</code> and 5.83% based on <code>mod2</code>), followed by black females (6.62% and 6.63%), white males (8.83% and 8.87%), and then white females (9.91% and 9.89%). This matches the trend we observed that those inferred to be white have a greater chance of getting a callback, regardless of gender, and that those who are inferred to be female have a slightly higher chance of getting a callback than those inferred to be male.</p>
</section>
<section id="exercise-5-evaluating-logistic-models-with-plots-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5-evaluating-logistic-models-with-plots-1">Exercise 5: Evaluating logistic models with plots</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(received_callback <span class="sc">~</span> gender<span class="sc">*</span>race <span class="sc">+</span> years_college <span class="sc">+</span> years_experience <span class="sc">+</span> resume_quality, <span class="at">data =</span> resume, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>mod1_output <span class="ot">&lt;-</span> <span class="fu">augment</span>(mod1, <span class="at">type.predict =</span> <span class="st">"response"</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>mod2_output <span class="ot">&lt;-</span> <span class="fu">augment</span>(mod2, <span class="at">type.predict =</span> <span class="st">"response"</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>mod3_output <span class="ot">&lt;-</span> <span class="fu">augment</span>(mod3, <span class="at">type.predict =</span> <span class="st">"response"</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod1_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="17_logistic_multivariate_evaluation_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod2_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="17_logistic_multivariate_evaluation_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod3_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="17_logistic_multivariate_evaluation_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>All 3 models show that those who actually received a callback had higher predicted probabilities of a callback. Models 1 and 2 are very similar–although predicted probabilites of callback are high for those who did actually receive a callback, there is substantial overlap in the boxplots. There is more separation between the boxplots in the third model, perhaps model 3 is best in terms of accuracy.</p></li>
<li><p>We would want to place the vertical lines such that as much of the left boxplot was below the line (low predicted probabilities for those with Y = 0) and as much of the right boxplot was above the line (high predicted probabilities for those with Y = 1).</p></li>
</ol>
</section>
<section id="exercise-6-evaluating-logistic-models-with-evaluation-metrics-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-6-evaluating-logistic-models-with-evaluation-metrics-1">Exercise 6: Evaluating logistic models with evaluation metrics</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod1_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.08</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="17_logistic_multivariate_evaluation_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod2_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.08</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="17_logistic_multivariate_evaluation_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mod3_output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(received_callback), <span class="at">y =</span> .fitted)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.08</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="17_logistic_multivariate_evaluation_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Next, we can use our threshold to classify each person in our dataset based on their predicted probability of getting a callback: we’ll predict that everyone with a predicted probability higher than our threshold got a callback, and otherwise they did not. Then, we’ll compare our model’s prediction to the true outcome (whether or not they actually did get a callback).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> <span class="fl">0.08</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>mod1_output <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">predictCallback =</span> .fitted <span class="sc">&gt;=</span> threshold) <span class="sc">%&gt;%</span> </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(received_callback, predictCallback) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  received_callback predictCallback     n
              &lt;dbl&gt; &lt;lgl&gt;           &lt;int&gt;
1                 0 FALSE            2278
2                 0 TRUE             2200
3                 1 FALSE             157
4                 1 TRUE              235</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>mod2_output <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">predictCallback =</span> .fitted <span class="sc">&gt;=</span> threshold) <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(received_callback, predictCallback)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  received_callback predictCallback     n
              &lt;dbl&gt; &lt;lgl&gt;           &lt;int&gt;
1                 0 FALSE            2278
2                 0 TRUE             2200
3                 1 FALSE             157
4                 1 TRUE              235</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>mod3_output <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">predictCallback =</span> .fitted <span class="sc">&gt;=</span> threshold) <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(received_callback, predictCallback)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  received_callback predictCallback     n
              &lt;dbl&gt; &lt;lgl&gt;           &lt;int&gt;
1                 0 FALSE            2465
2                 0 TRUE             2013
3                 1 FALSE             159
4                 1 TRUE              233</code></pre>
</div>
</div>
<ol type="a">
<li></li>
</ol>
<blockquote class="blockquote">
<p>Models 1 and 2: (Both models result in the same confusion matrix.)</p>
</blockquote>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Predict callback</th>
<th style="text-align: center;">Predict no callback</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Actually got callback</td>
<td style="text-align: center;">235</td>
<td style="text-align: center;">157</td>
<td style="text-align: center;">392</td>
</tr>
<tr class="even">
<td>Actually did not</td>
<td style="text-align: center;">2200</td>
<td style="text-align: center;">2278</td>
<td style="text-align: center;">4478</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: center;">2435</td>
<td style="text-align: center;">2435</td>
<td style="text-align: center;">4870</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>Model 3:</p>
</blockquote>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Predict callback</th>
<th style="text-align: center;">Predict no callback</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Actually got callback</td>
<td style="text-align: center;">233</td>
<td style="text-align: center;">159</td>
<td style="text-align: center;">392</td>
</tr>
<tr class="even">
<td>Actually did not</td>
<td style="text-align: center;">2013</td>
<td style="text-align: center;">2465</td>
<td style="text-align: center;">4478</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: center;">2246</td>
<td style="text-align: center;">2624</td>
<td style="text-align: center;">4870</td>
</tr>
</tbody>
</table>
<ol start="2" type="a">
<li>Now compute the following evaluation metrics for the models:</li>
</ol>
<blockquote class="blockquote">
<p>Models 1 and 2:</p>
<ul>
<li>Accuracy: P(Predict Y Correctly) = (TP + TN)/(TP + FN + FP + TN) = (235 + 2278)/(235 + 157 + 2200 + 2278) = 0.5160164</li>
<li>Sensitivity: P(Predict Y = 1 | Actual Y = 1) = TP/(TP + FN) = 235/(235 + 157) = 0.5994898</li>
<li>Specificity: P(Predict Y = 0 | Actual Y = 0) = TN/(TN + FP) = 2278/(2200 + 2278) = 0.5087092</li>
<li>False negative rate: P(Predict Y = 0 | Actual Y = 1) = FN/(TP + FN) = 157/(235 + 157) = 0.4005102 (notice that this is equal to 1 - Sensitivity)</li>
<li>False positive rate: P(Predict Y = 1 | Actual Y = 0) = FP/(FP + TN) = 2200/(2200 + 2278) = 0.4912908 (notice that this is equal to 1 - Specificity)</li>
</ul>
</blockquote>
<blockquote class="blockquote">
<p>Model 3:</p>
<ul>
<li>Accuracy: P(Predict Y Correctly) = (TP + TN)/(TP + FN + FP + TN) = (233 + 2465)/(233 + 159 + 2013 + 2465) = 0.5540041</li>
<li>Sensitivity: P(Predict Y = 1 | Actual Y = 1) = TP/(TP + FN) = 233/(233 + 159) = 0.5943878</li>
<li>Specificity: P(Predict Y = 0 | Actual Y = 0) = TN/(TN + FP) = 2465/(2013 + 2465) = 0.550469</li>
<li>False negative rate: P(Predict Y = 0 | Actual Y = 1) = FN/(TP + FN) = 159/(233 + 159) = 0.4056122 (notice that this is equal to 1 - Sensitivity)</li>
<li>False positive rate: P(Predict Y = 1 | Actual Y = 0) = FP/(FP + TN) = 2013/(2013 + 2465) = 0.449531 (notice that this is equal to 1 - Specificity)</li>
</ul>
</blockquote>
<ol start="3" type="a">
<li>Imagine that we are a career center on a college campus and we want to use this model to help students that are looking for jobs. Consider the consequences of incorrectly predicting whether or not an individual will get a callback. What are the consequences of a false negative? What about a false positive? Which one is worse?
<ul>
<li>False Negatives (predicting no callback, but actually got callback): this would be a lost opportunity if a student decided not to submit their resume, thinking they wouldn’t get a callback, when actually they would have.</li>
<li>False Positives (predicting callback, but actually didn’t get callback): this would be a disappointment for the student, thinking they were going to get a callback but they ended up not getting one.</li>
</ul></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Leslie Myint, 2024<br> All content licensed under <img src="https://static.thenounproject.com/png/70967-200.png" height="20"> (<a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>)</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Site built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>