<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Nested Models &amp; F-Tests – STAT 155</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../activities/01_foundations_welcome.html">Activities</a></li><li class="breadcrumb-item"><a href="../activities/25_f_tests.html">Nested Models &amp; F-Tests</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">STAT 155</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Activities</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/01_foundations_welcome.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Fundamentals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/02_foundations_univariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Univariate visualization and summaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/03_slr_introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple linear regression: Visualization and Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/04_slr_formalization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple linear regression: formalizing concepts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/05_slr_model_eval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple linear regression: model evaluation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/06_slr_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple linear regression: Transformations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/07_slr_cat_predictor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple linear regression: categorical predictor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/08_mlr_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to multiple regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/09_mlr_principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple regression principles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/10_mlr_confounding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Confounding variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/11_mlr_interaction_explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple linear regression: exploring interaction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/12_mlr_interaction_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple linear regression: interaction terms practice</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/13_mlr_model_building_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple linear regression: model building (part 1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/14_mlr_model_building_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple linear regression: model building (part 2)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/15_prob_odds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability and Odds</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/16_logistic_univariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/17_logistic_multivariate_evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/18_sampling_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Normal model &amp; sampling variation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/19_sampling_dist_clt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sampling distributions &amp; the CLT</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/20_bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrapping</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/21_confidence_intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/22_hypothesis_testing_discovery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis testing: discovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/23_hypothesis_testing_details.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis testing details</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/24_hypothesis_testing_considerations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis testing: additional considerations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../activities/25_f_tests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Nested Models &amp; F-Tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Homework</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pp8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practice Problems 8</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../r_resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Resources</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#notes" id="toc-notes" class="nav-link active" data-scroll-target="#notes">Notes</a>
  <ul class="collapse">
  <li><a href="#learning-goals" id="toc-learning-goals" class="nav-link" data-scroll-target="#learning-goals">Learning goals</a></li>
  <li><a href="#readings-and-videos" id="toc-readings-and-videos" class="nav-link" data-scroll-target="#readings-and-videos">Readings and videos</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#nested-models" id="toc-nested-models" class="nav-link" data-scroll-target="#nested-models">Nested models</a></li>
  <li><a href="#example-house-prices" id="toc-example-house-prices" class="nav-link" data-scroll-target="#example-house-prices">Example: house prices</a></li>
  <li><a href="#example-résumés" id="toc-example-résumés" class="nav-link" data-scroll-target="#example-résumés">Example: résumés</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
  <li><a href="#exercise-1-nested-models" id="toc-exercise-1-nested-models" class="nav-link" data-scroll-target="#exercise-1-nested-models">Exercise 1: Nested Models</a></li>
  <li><a href="#exercise-2-f-tests" id="toc-exercise-2-f-tests" class="nav-link" data-scroll-target="#exercise-2-f-tests">Exercise 2: F-Tests</a></li>
  <li><a href="#exercise-3-more-f-tests" id="toc-exercise-3-more-f-tests" class="nav-link" data-scroll-target="#exercise-3-more-f-tests">Exercise 3: More F-tests</a></li>
  <li><a href="#reflection" id="toc-reflection" class="nav-link" data-scroll-target="#reflection">Reflection</a></li>
  </ul></li>
  <li><a href="#additional-practice" id="toc-additional-practice" class="nav-link" data-scroll-target="#additional-practice">Additional Practice</a>
  <ul class="collapse">
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4">Exercise 4</a></li>
  <li><a href="#exercise-5-reference-categories" id="toc-exercise-5-reference-categories" class="nav-link" data-scroll-target="#exercise-5-reference-categories">Exercise 5: Reference categories</a></li>
  </ul></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions">Solutions</a>
  <ul class="collapse">
  <li><a href="#exercise-1-nested-models-1" id="toc-exercise-1-nested-models-1" class="nav-link" data-scroll-target="#exercise-1-nested-models-1">Exercise 1: Nested Models</a></li>
  <li><a href="#exercise-2-f-tests-1" id="toc-exercise-2-f-tests-1" class="nav-link" data-scroll-target="#exercise-2-f-tests-1">Exercise 2: F-Tests</a></li>
  <li><a href="#exercise-3-more-f-tests-1" id="toc-exercise-3-more-f-tests-1" class="nav-link" data-scroll-target="#exercise-3-more-f-tests-1">Exercise 3: More F-tests</a></li>
  <li><a href="#exercise-4-1" id="toc-exercise-4-1" class="nav-link" data-scroll-target="#exercise-4-1">Exercise 4</a></li>
  <li><a href="#exercise-5-reference-categories-1" id="toc-exercise-5-reference-categories-1" class="nav-link" data-scroll-target="#exercise-5-reference-categories-1">Exercise 5: Reference categories</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../activities/01_foundations_welcome.html">Activities</a></li><li class="breadcrumb-item"><a href="../activities/25_f_tests.html">Nested Models &amp; F-Tests</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Nested Models &amp; F-Tests</h1>
<p class="subtitle lead">Notes and in-class exercises</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="notes" class="level1">
<h1>Notes</h1>
<ul>
<li>You can download a template file to work with <a href="../activity_templates/25_f_tests.qmd">here</a>.</li>
<li><strong>File organization:</strong> Save this file in the “Activities” subfolder of your “STAT155” folder.</li>
</ul>
<section id="learning-goals" class="level2">
<h2 class="anchored" data-anchor-id="learning-goals">Learning goals</h2>
<p>By the end of this activity, you should be able to:</p>
<ul>
<li>Determine if one model is nested within another</li>
<li>Determine which null and alternative hypotheses require an f-test</li>
<li>Determine which f-tests require the use of the <code>anova</code> function in R vs.&nbsp;the overall f-test given in regular regression output</li>
<li>Interpret the results of an f-test in context</li>
</ul>
</section>
<section id="readings-and-videos" class="level2">
<h2 class="anchored" data-anchor-id="readings-and-videos">Readings and videos</h2>
<p>Please read the following notes <strong>before</strong> class:</p>
<ul>
<li>Reading: Section 7.3.4 in the <a href="https://mac-stat.github.io/Stat155Notes/">STAT 155 Notes</a></li>
</ul>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="nested-models" class="level3">
<h3 class="anchored" data-anchor-id="nested-models">Nested models</h3>
<p>“Nested models” are models where the covariates of one model are a subset of another model.</p>
<p>As an example, consider the following models for estimating the association between forced expiratory volume (FEV) and smoking status:</p>
<p><strong>Model 1:</strong></p>
<p><span class="math display">\[
E[FEV \mid smoke] = \beta_0 + \beta_1 smoke
\]</span></p>
<p><strong>Model 2:</strong></p>
<p><span class="math display">\[
E[FEV \mid smoke, age] = \beta_0 + \beta_1 smoke + \beta_2 age
\]</span></p>
<p>Here, Model 1 is “nested” inside Model 2, since the covariates included in Model 1 (only <em>smoke</em>) are a subset of those in Model 2 (both <em>smoke</em> and <em>age</em>).</p>
<p>An example of non-nested models are…</p>
<p><strong>Model 3:</strong></p>
<p><span class="math display">\[
E[FEV \mid smoke, height] = \beta_0 + \beta_1 smoke + \beta_2 height
\]</span></p>
<p><strong>Model 4:</strong></p>
<p><span class="math display">\[
E[FEV \mid smoke, sex] = \beta_0 + \beta_1 smoke + \beta_2 sex
\]</span></p>
<p>Here, even though Model 3 and Model 4 both contain <em>smoke</em> as explanatory variables, neither is nested in the other, since <em>sex</em> is not a part of Model 3, and <em>height</em> is not a part of Model 4.</p>
<p><strong>Why should we care about nested models?</strong></p>
<p>Comparing nested models provides us a way of looking at the usefulness of multiple coefficients at the same time. Looking at multiple coefficients is relevant when…</p>
<ul>
<li>we are adding a single categorical predictor with &gt;2 categories to a model</li>
<li>we are adding several different predictors to a model</li>
</ul>
</section>
<section id="example-house-prices" class="level3">
<h3 class="anchored" data-anchor-id="example-house-prices">Example: house prices</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>homes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://mac-stat.github.io/data/homes.csv"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>homes <span class="ot">&lt;-</span> homes <span class="sc">%&gt;%</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(Fuel.Type, Heat.Type, Sewer.Type), factor))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Research question:</strong> Does fuel type provide meaningful additional information on house price after considering square footage (<code>Living.Area</code>) and <code>Age</code>?</p>
<ul>
<li>How can we use adjusted R-squared to answer this question? (Why would we use adjusted R-squared instead of multiple R-squared?)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>homes_mod_small <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Living.Area <span class="sc">+</span> Age, <span class="at">data =</span> homes)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>homes_mod_large <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Living.Area <span class="sc">+</span> Age <span class="sc">+</span> Fuel.Type, <span class="at">data =</span> homes)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(homes_mod_small)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Living.Area + Age, data = homes)

Residuals:
    Min      1Q  Median      3Q     Max 
-267300  -40485   -8491   27303  557613 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 22951.791   5536.960   4.145 3.56e-05 ***
Living.Area   111.277      2.713  41.019  &lt; 2e-16 ***
Age          -224.751     57.576  -3.904 9.84e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 68820 on 1725 degrees of freedom
Multiple R-squared:  0.5118,    Adjusted R-squared:  0.5112 
F-statistic: 904.2 on 2 and 1725 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(homes_mod_large)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Living.Area + Age + Fuel.Type, data = homes)

Residuals:
    Min      1Q  Median      3Q     Max 
-258471  -39727   -8018   27248  550481 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  32778.478   6091.930   5.381 8.44e-08 ***
Living.Area    108.202      2.823  38.323  &lt; 2e-16 ***
Age           -230.127     60.046  -3.833 0.000131 ***
Fuel.Type3  -16699.878   4545.204  -3.674 0.000246 ***
Fuel.Type4   -9886.096   5270.819  -1.876 0.060875 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 68560 on 1723 degrees of freedom
Multiple R-squared:  0.5161,    Adjusted R-squared:  0.5149 
F-statistic: 459.3 on 4 and 1723 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We can also use the <code>anova()</code> function to approach our research question:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(homes_mod_small, homes_mod_large)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Price ~ Living.Area + Age
Model 2: Price ~ Living.Area + Age + Fuel.Type
  Res.Df        RSS Df  Sum of Sq      F   Pr(&gt;F)    
1   1725 8.1702e+12                                  
2   1723 8.0991e+12  2 7.1167e+10 7.5701 0.000533 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>Null and alternative hypotheses:
<ul>
<li><span class="math inline">\(H_0\)</span>: There is NO relationship between fuel type and house price after accounting for house size and age.</li>
<li><span class="math inline">\(H_A\)</span>: There IS a relationship between fuel type and house price after accounting for house size and age.</li>
</ul></li>
<li>Test statistic: 7.57
<ul>
<li>The number in row 2 in the F column.</li>
<li>Doesn’t have a nice interpretation as “standard errors away from the null” like we do when testing single coefficients.</li>
<li>Null value is 1 because the F statistic is a ratio of variances.</li>
</ul></li>
<li>P-value: 0.000533
<ul>
<li>The number in row 2 in the Pr(&gt;F) column.</li>
<li>We’ll use a significance level of 0.05.</li>
<li>Because this p-value is less than our significance level, we would reject the null hypothesis: we do have evidence for a relationship between fuel type and house price after accounting for house size and age.</li>
</ul></li>
</ul>
</section>
<section id="example-résumés" class="level3">
<h3 class="anchored" data-anchor-id="example-résumés">Example: résumés</h3>
<p>We are interested in exploring résumé characteristics that relate to the odds of an applicant receiving a callback.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>resume <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://mac-stat.github.io/data/resume.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 4870 Columns: 30
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (10): job_city, job_industry, job_type, job_ownership, job_req_min_exper...
dbl (20): job_ad_id, job_fed_contractor, job_equal_opp_employer, job_req_any...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p><strong>Research question:</strong> Does the collective presence of special skills and computer skills provide meaningful additional information on the odds of receiving a callback after considering an applicant’s inferred race and gender?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>resume_mod_small <span class="ot">&lt;-</span> <span class="fu">glm</span>(received_callback <span class="sc">~</span> race <span class="sc">+</span> gender, <span class="at">data =</span> resume, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>resume_mod_large <span class="ot">&lt;-</span> <span class="fu">glm</span>(received_callback <span class="sc">~</span> race <span class="sc">+</span> gender <span class="sc">+</span> special_skills <span class="sc">+</span> computer_skills, <span class="at">data =</span> resume, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(resume_mod_small, resume_mod_large)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: received_callback ~ race + gender
Model 2: received_callback ~ race + gender + special_skills + computer_skills
  Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
1      4867     2708.9                          
2      4865     2648.7  2   60.233 8.328e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>Null and alternative hypotheses:
<ul>
<li><span class="math inline">\(H_0\)</span>: Special skills and computer skills collectively DO NOT provide meaningful additional information on the odds of receiving a callback after considering an applicant’s inferred race and gender.</li>
<li><span class="math inline">\(H_A\)</span>: Special skills and computer skills collectively DO provide meaningful additional information on the odds of receiving a callback after considering an applicant’s inferred race and gender.</li>
</ul></li>
<li>Test statistic: 60.233
<ul>
<li>The number in row 2 in the Deviance column.</li>
<li>Doesn’t have a nice interpretation as “standard errors away from the null” like we do when testing single coefficients.</li>
<li>Null value is 1 because this statistic is a ratio of likelihoods.</li>
</ul></li>
<li>P-value: 8.328e-14
<ul>
<li>The number in row 2 in the Pr(&gt;Chi) column.</li>
<li>We’ll use a significance level of 0.05.</li>
<li>Because this p-value is less than our significance level, we would reject the null hypothesis: we do have evidence that special skills and computer skills collectively provide meaningful additional information on the odds of receiving a callback after considering an applicant’s inferred race and gender.</li>
</ul></li>
</ul>
</section>
</section>
</section>
<section id="exercises" class="level1">
<h1>Exercises</h1>
<section id="exercise-1-nested-models" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1-nested-models">Exercise 1: Nested Models</h2>
<ol type="a">
<li>Which of the following models are nested in the model <span class="math inline">\(E[A \mid B, C, D] = \beta_0 + \beta_1 D + \beta_2 B + \beta_3 C + \beta_4 B * C\)</span>?</li>
</ol>
<ul>
<li>Model 1: <span class="math inline">\(E[A \mid B] = \beta_0 + \beta_1 B\)</span></li>
<li>Model 2: <span class="math inline">\(E[A \mid B, D] = \beta_0 + \beta_1 B + \beta_2 D\)</span></li>
<li>Model 3: <span class="math inline">\(E[B \mid C] = \beta_0 + \beta_1 C\)</span></li>
<li>Model 4: <span class="math inline">\(E[A \mid B, C, D] = \beta_0 + \beta_1 B + \beta_2 C + \beta_3 D\)</span></li>
<li>Model 5: <span class="math inline">\(E[A \mid B, C, D] = \beta_0 + \beta_1 C + \beta_2 B + \beta_3 D + \beta_4 B * D\)</span></li>
<li>Model 6: <span class="math inline">\(E[A \mid D] = \beta_0 + \beta_1 D\)</span></li>
</ul>
<ol start="2" type="a">
<li>Consider the following models involving variables A, B, C, and D:</li>
</ol>
<ul>
<li>Model 1: <span class="math inline">\(E[A \mid B] = \beta_0 + \beta_1 B\)</span></li>
<li>Model 2: <span class="math inline">\(E[A \mid B, C] = \beta_0 + \beta_1 B + \beta_2 C\)</span></li>
<li>Model 3: <span class="math inline">\(E[A \mid B, C] = \beta_0 + \beta_1 B + \beta_2 C + \beta_3 BC\)</span></li>
<li>Model 4: <span class="math inline">\(E[A \mid C, D] = \beta_0 + \beta_1 C + \beta_2 D\)</span></li>
<li>Model 5: <span class="math inline">\(E[B \mid A] = \beta_0 + \beta_1 A\)</span></li>
<li>Model 6: <span class="math inline">\(E[B \mid A, C] = \beta_0 + \beta_1 A + \beta_2 C + \beta_3 AC\)</span></li>
</ul>
<p>Determine for each of the following statements whether that statement is True or False.</p>
<ul>
<li>Model 1 is nested in Model 2</li>
<li>Model 1 is nested in Model 3</li>
<li>Model 1 is nested in Model 4</li>
<li>Model 2 is nested in Model 3</li>
<li>Model 3 is nested in Model 2</li>
<li>Model 2 is nested in Model 6</li>
</ul>
<ol start="3" type="a">
<li>What is one (numeric) way to compare nested models? Explain how you would determine which model is “better” based on this metric.</li>
</ol>
</section>
<section id="exercise-2-f-tests" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2-f-tests">Exercise 2: F-Tests</h2>
<p>This exercise involves the <code>MacGrades.csv</code> dataset, which contains a sub-sample (to help preserve anonymity) of every grade assigned to a former Macalester graduating class. For each of the 6414 rows of data, the following information is provided (with a few missing values):</p>
<ul>
<li><code>sessionID</code>: A section ID number</li>
<li><code>sid</code>: A student ID number</li>
<li><code>grade</code>: The grade obtained, as a numerical value (i.e.&nbsp;an A is a 4, an A- is a 3.67, etc.)</li>
<li><code>dept</code>: A department identifier (these have been made ambiguous to maintain anonymity)</li>
<li><code>level</code>: The course level (e.g.&nbsp;100-, 200-, 300-, and 600-)</li>
<li><code>sem</code>: A semester identifier</li>
<li><code>enroll</code>: The section enrollment</li>
<li><code>iid</code>: An instructor identifier (these have been made ambiguous to maintain anonymity)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load necessary packages</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># load datasets</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>MacGrades <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://mac-stat.github.io/data/MacGrades.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="a">
<li>Hypothesize the relationships between the variables in the dataset. Your response should include at least five sentences, at a minimum. If you find it useful, you may also draw a DAG for this question.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Response</strong> Put your response here</p>
</blockquote>
<ol start="2" type="a">
<li><p>Explore the relationship between course grades and other variables in the data. Make at least four visualizations, <em>and</em> describe any patterns you observe.</p></li>
<li><p>Note that the <code>level</code> variable is currently quantitative. For this activity, we’d like to treat it as categorical. Create a new variable <code>level_cat</code> so that we can consider level categorically in the following analysis.</p></li>
<li><p>Suppose we are interested in the relationship between course level (categorical) and student grades. Using grade as your outcome variable, fit a linear regression model to investigate this question.</p></li>
</ol>
<p>Comment on the nature of the relationship between course level and student grades (this should not be a coefficient interpretation, but instead a description of a general trend, or lack thereof).</p>
<ol start="5" type="a">
<li>State the null and alternative hypotheses associated with the research question in part (d).</li>
</ol>
<p><span class="math display">\[
H_0:
\]</span></p>
<p><span class="math display">\[
H_1:
\]</span></p>
<ol start="6" type="a">
<li><p>What is the p-value associated with this hypothesis test? Do we have enough evidence to reject the null hypothesis, using a significance threshold of 0.05?</p></li>
<li><p>Suppose we are interested in the relationship between course enrollment and student grades. Again, use grade as your outcome variable, and fit a linear regression model to investigate this question.</p></li>
<li><p>State the null and alternative hypotheses associated with the research question in part (g).</p></li>
</ol>
<p><span class="math display">\[
H_0:
\]</span></p>
<p><span class="math display">\[
H_1:
\]</span></p>
<ol type="i">
<li>What is the p-value associated with this hypothesis test? Do we have enough evidence to reject the null hypothesis, using a significance threshold of 0.05?</li>
</ol>
<ol start="10" type="a">
<li>Do we need to conduct a <em>nested</em> F-test using the <code>anova</code> function to complete our hypothesis testing procedure for the research question posed in part (g)? Explain why or why not.</li>
</ol>
</section>
<section id="exercise-3-more-f-tests" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3-more-f-tests">Exercise 3: More F-tests</h2>
<ol type="a">
<li>Suppose we are now interested in the association between course grade and enrollment for classes of the same level. Write a model statement in the form <span class="math inline">\(E[Y | X] = ...\)</span> that will produce a statistical model that will allow us to answer our scientific question. Replace Y and X, where appropriate, with response and predictor variables.</li>
</ol>
<p><span class="math display">\[
E[Y | X] = ___
\]</span></p>
<p>Which coefficient(s) in your model is the one that is relevant to your research question?</p>
<ol start="2" type="a">
<li><p>What are the relevant null and alternative hypotheses that address the scientific question in part (a)?</p></li>
<li><p>Fit the model you wrote in part (a), calculate a p-value, and report the results of the hypothesis test in part (b).</p></li>
</ol>
</section>
<section id="reflection" class="level2">
<h2 class="anchored" data-anchor-id="reflection">Reflection</h2>
<p>F-tests are useful when the null hypothesis you wish to test is such that <em>more than one</em> covariate is simultaneously equal to a specific number (typically zero). What scenarios, outside of those shown in this example, can you think of where a relevant scientific hypothesis you want to test involves more than one covariate being simultaneously equal to zero?</p>
<blockquote class="blockquote">
<p><strong>Response</strong> Put your response here.</p>
</blockquote>
</section>
</section>
<section id="additional-practice" class="level1">
<h1>Additional Practice</h1>
<section id="exercise-4" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4">Exercise 4</h2>
<p>Repeat Exercise 3, supposing we are instead interested in the association between course grade and course level for classes of the same enrollment.</p>
</section>
<section id="exercise-5-reference-categories" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5-reference-categories">Exercise 5: Reference categories</h2>
<p>Our final research question pertains to whether or not there is a relationship between course grade and department. Again, use course grade as the outcome variable in your linear regression model.</p>
<ol type="a">
<li>State the null and alternative hypotheses <em>in colloquial language</em> associated with the relevant hypothesis test.</li>
</ol>
<p>H0:</p>
<p>H1:</p>
<ol start="2" type="a">
<li><p>Fit a linear regression model, and conduct your hypothesis testing procedure to answer the research question posed in this Exercise. State your conclusions accordingly (you do not need to interpret any regression coefficients, just state and interpret the results of your hypothesis test!).</p></li>
<li><p>Are any of the individual department p-values significant?</p></li>
</ol>
<p>What do these p-values tell us, and why is this <em>not</em> contradictory to your answer in part (b)?</p>
<p><br><br><br><br><br><br></p>
</section>
</section>
<section id="solutions" class="level1">
<h1>Solutions</h1>
<section id="exercise-1-nested-models-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1-nested-models-1">Exercise 1: Nested Models</h2>
<ol type="a">
<li><p>Models 1, 2, 4 and 6.</p></li>
<li></li>
</ol>
<ul>
<li>Model 1 is nested in Model 2 TRUE</li>
<li>Model 1 is nested in Model 3 TRUE</li>
<li>Model 1 is nested in Model 4 FALSE</li>
<li>Model 2 is nested in Model 3 TRUE</li>
<li>Model 3 is nested in Model 2 FALSE</li>
<li>Model 2 is nested in Model 6 FALSE</li>
</ul>
<ol start="3" type="a">
<li>You could compare the Adjusted <span class="math inline">\(R^2\)</span> values from each model, and note that the one with a higher adjusted <span class="math inline">\(R^2\)</span> is better by this metric. Multiple <span class="math inline">\(R^2\)</span> would <em>not</em> be a good metric, because the larger model (within the nesting structure) will <em>always</em> have a higher <span class="math inline">\(R^2\)</span> value.</li>
</ol>
</section>
<section id="exercise-2-f-tests-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2-f-tests-1">Exercise 2: F-Tests</h2>
<ol type="a">
<li><p>It is reasonable to assume that course grade varies by department as well as course level and instructor. Certain instructors may grade more strictly (or curve more) than others, and similarly, this can vary across department due to cultural norms within the department. As the level of a course gets higher, I would expect grades to perhaps get lower, since courses with higher numbers are expected to be more difficult. Then again, students perhaps “care” more about such courses, and may put in more effort to get a higher grade. I doubt semester plays a significant role in determining course grades, though it is possible that Fall semester first-years or Spring semester seniors have worse grades, on average. We don’t have course year as a variable in our data, so we would be unable to examine this relationship. As enrollment in a course goes up, I would expect grades to decrease, since professors have less time to dedicate to individual students when course enrollment is high.</p></li>
<li><p>Explore the relationship between course grades and other variables in the data. Make at least four visualizations, <em>and</em> describe any patterns you observe.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Exploratory plots</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># course grade vs. enrollment</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>MacGrades <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(enroll, grade)) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Course grades by enrollment numbers"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="25_f_tests_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># course grade vs. level</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>MacGrades <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="fu">factor</span>(level)) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> grade, <span class="at">x =</span> level)) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Course grades by course level"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="25_f_tests_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># course grade vs. level (treating grade as categorical)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>MacGrades <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(grade)) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="fu">factor</span>(level),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">grade =</span> <span class="fu">factor</span>(grade)) <span class="sc">%&gt;%</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> level, <span class="at">fill =</span> grade)) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"H"</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Course grades by course level"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="25_f_tests_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># course grade vs. semester</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>MacGrades <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(grade)) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grade =</span> <span class="fu">factor</span>(grade)) <span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sem, <span class="at">fill =</span> grade)) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"H"</span>) <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Course grades by semester"</span>) <span class="sc">+</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="25_f_tests_files/figure-html/unnamed-chunk-7-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's do something fancy and check out how grades have changed over time... this will require</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># some string manipulation</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>MacGrades<span class="sc">$</span>year <span class="ot">&lt;-</span> MacGrades<span class="sc">$</span>sem <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_replace</span>(<span class="st">"FA"</span>, <span class="st">""</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_replace</span>(<span class="st">"SP"</span>, <span class="st">""</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_replace</span>(<span class="st">"S1"</span>, <span class="st">""</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_replace</span>(<span class="st">"S2"</span>, <span class="st">""</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_replace</span>(<span class="st">"IT"</span>, <span class="st">""</span>) <span class="sc">%&gt;%</span> <span class="fu">as.numeric</span>()</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>MacGrades <span class="sc">%&gt;%</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(year, grade)) <span class="sc">+</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Course grades by year, with least-squares line"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="25_f_tests_files/figure-html/unnamed-chunk-7-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In general, course grades seem to be associated with enrollment numbers. Specifically, when enrollments are greater than 50, we see very few students receiving a course grade lower than a 2.0, which is different than when enrollments are fewer than 50 students. There does not appear to be a clear relationship between course grade and course level, with the exception of 600-level courses. In these cases, every student received either an A or A-. It does seem like the proportion of students who received lower than a 2.67 is greater for 100-level courses than the other course levels.</p>
<ol start="3" type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make level categorical</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>MacGrades <span class="ot">&lt;-</span> MacGrades <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="fu">factor</span>(level))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="4" type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> level, <span class="at">data =</span> MacGrades)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = grade ~ level, data = MacGrades)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4776 -0.3492  0.2089  0.5224  0.6508 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.34924    0.01208 277.166  &lt; 2e-16 ***
level200     0.11183    0.01995   5.606 2.17e-08 ***
level300     0.09078    0.01949   4.659 3.25e-06 ***
level400     0.12835    0.03168   4.052 5.15e-05 ***
level600     0.63339    0.13624   4.649 3.41e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5915 on 5704 degrees of freedom
  (437 observations deleted due to missingness)
Multiple R-squared:  0.01085,   Adjusted R-squared:  0.01016 
F-statistic: 15.65 on 4 and 5704 DF,  p-value: 9.713e-13</code></pre>
</div>
</div>
<p>We observe that as course level goes up, course grades also tend to increase on average.</p>
<ol start="5" type="a">
<li>State the null and alternative hypotheses associated with the research question in part (d).</li>
</ol>
<p><span class="math display">\[
H_0: \beta_1 = \beta_2 = \beta_3 = \beta_4 = 0
\]</span></p>
<p><span class="math display">\[
H_1: \text{One of } \beta_1, \beta_2, \beta_3, \beta_4 \neq 0
\]</span></p>
<p>In words, the null is that there is <em>no</em> relationship between course level and course grades, and the alternative is that there is <em>some</em> relationship (either positive or negative) between course level and course grades.</p>
<ol start="6" type="a">
<li><p>The p-value associated with this hypothesis test is 9.713 x <span class="math inline">\(10^{-13}\)</span>. We do have enough evidence to reject the null hypothesis.</p></li>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> enroll, <span class="at">data =</span> MacGrades)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = grade ~ enroll, data = MacGrades)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4529 -0.3871  0.2265  0.5534  0.8448 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.4842350  0.0173790 200.485  &lt; 2e-16 ***
enroll      -0.0031336  0.0006683  -4.689 2.81e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5934 on 5707 degrees of freedom
  (437 observations deleted due to missingness)
Multiple R-squared:  0.003838,  Adjusted R-squared:  0.003664 
F-statistic: 21.99 on 1 and 5707 DF,  p-value: 2.806e-06</code></pre>
</div>
</div>
<ol start="8" type="a">
<li></li>
</ol>
<p><span class="math display">\[
H_0: \beta_1 = 0
\]</span></p>
<p><span class="math display">\[
H_1: \beta_1 \neq 0
\]</span></p>
<ol type="i">
<li>The p-value associated with this hypothesis test is 2.806 x <span class="math inline">\(10^{-06}\)</span>. We do have enough evidence to reject the null hypothesis. Note that this p-value could be obtained from either the overall model fit or from the individual coefficient for enroll (they are the same). They may be ever so slightly different when there are few observations in your dataset, but when there are a lot, they will be exactly identical.</li>
</ol>
<ol start="10" type="a">
<li>We do <em>not</em> need to conduct an F-test, because our hypothesis test involves only a single regression coefficient, and therefore is readily obtained from the summary output of our linear model in R.</li>
</ol>
</section>
<section id="exercise-3-more-f-tests-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3-more-f-tests-1">Exercise 3: More F-tests</h2>
<ol type="a">
<li></li>
</ol>
<p><span class="math display">\[
E[grade | enroll, level] = \beta_0 + \beta_1 enroll + \beta_2 level200 + \beta_3 level300 + \beta_4 level400 + \beta_5 level600
\]</span></p>
<p>The relevant coefficient that answers our scientific question is <span class="math inline">\(\beta_1\)</span>, or the coefficient that corresponds to enrollment.</p>
<ol start="2" type="a">
<li></li>
</ol>
<p>The relevant null and alternative hypotheses are:</p>
<p><span class="math display">\[
H_0: \beta_1 = 0
\]</span></p>
<p><span class="math display">\[
H_1: \beta_1 \neq 0
\]</span> We do not need to conduct an F-test to complete this hypothesis testing procedure, since our hypothesis involves only a single regression coefficient.</p>
<ol start="3" type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> enroll <span class="sc">+</span> level, <span class="at">data =</span> MacGrades)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = grade ~ enroll + level, data = MacGrades)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4916 -0.3481  0.1907  0.5162  0.7764 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.4091632  0.0219143 155.568  &lt; 2e-16 ***
enroll      -0.0022628  0.0006907  -3.276 0.001058 ** 
level200     0.1040873  0.0200701   5.186 2.22e-07 ***
level300     0.0743387  0.0201066   3.697 0.000220 ***
level400     0.1118660  0.0320492   3.490 0.000486 ***
level600     0.6182478  0.1361974   4.539 5.76e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.591 on 5703 degrees of freedom
  (437 observations deleted due to missingness)
Multiple R-squared:  0.01271,   Adjusted R-squared:  0.01185 
F-statistic: 14.69 on 5 and 5703 DF,  p-value: 2.453e-14</code></pre>
</div>
</div>
<p>We have statistically significant evidence of a relationship between enrollment and course grade, for courses of the same level (p = 0.001058). We reject the null hypothesis that there is no relationship between enrollment and course grade, adjusting for course level.</p>
</section>
<section id="exercise-4-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4-1">Exercise 4</h2>
<p>Our model statement is identical to that in Exercise 3, but the relevant coefficients are <span class="math inline">\(\beta_2, \beta_3, \beta_4\)</span>, and <span class="math inline">\(\beta_5\)</span>.</p>
<p>The relevant null and alternative hypotheses are:</p>
<p><span class="math display">\[
H_0: \beta_2 = \beta_3 = \beta_4 = \beta_5 = 0
\]</span></p>
<p><span class="math display">\[
H_1: \text{At least one of } \beta_2, \beta_3, \beta_4, \beta_5 \neq 0
\]</span></p>
<p>We <em>do</em> need to conduct an F-test to complete this hypothesis testing procedure, since our hypothesis involves more than one regression coefficient.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Same model as in Question 10, we just now need to do an F-test!</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> enroll <span class="sc">+</span> level, <span class="at">data =</span> MacGrades)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>smaller_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> enroll, <span class="at">data =</span> MacGrades)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(smaller_mod, mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: grade ~ enroll
Model 2: grade ~ enroll + level
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)    
1   5707 2009.8                                 
2   5703 1991.9  4    17.904 12.815 2.19e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We have statistically significant evidence of a relationship between course level and course grade, for courses of the same enrollment (<span class="math inline">\(p = 2.19 \times 10^{-10}\)</span>). We reject the null hypothesis that there is no relationship between course level and course grade, adjusting for enrollment.</p>
</section>
<section id="exercise-5-reference-categories-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5-reference-categories-1">Exercise 5: Reference categories</h2>
<ol type="a">
<li></li>
</ol>
<p>H0: There is no relationship between course grade and department.</p>
<p>H1: There is <em>some</em> relationship between course grade and department.</p>
<ol start="2" type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> dept, <span class="at">data =</span> MacGrades)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = grade ~ dept, data = MacGrades)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.5268 -0.2749  0.1475  0.4515  0.9039 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.5000000  0.4088676   8.560   &lt;2e-16 ***
deptb       -0.2536066  0.4155163  -0.610    0.542    
deptB       -0.2614286  0.4278948  -0.611    0.541    
deptC        0.0268398  0.4106338   0.065    0.948    
deptd       -0.1825995  0.4098240  -0.446    0.656    
deptD        0.0617623  0.4105399   0.150    0.880    
depte       -0.0162500  0.4122607  -0.039    0.969    
deptE        0.1391667  0.4416275   0.315    0.753    
deptF       -0.2251373  0.4104679  -0.548    0.583    
deptg        0.0956522  0.4176615   0.229    0.819    
deptG       -0.3303306  0.4105537  -0.805    0.421    
deptH       -0.0307813  0.4120495  -0.075    0.940    
depti       -0.1474011  0.4111711  -0.358    0.720    
deptI        0.0011538  0.4243020   0.003    0.998    
deptj       -0.0625248  0.4108867  -0.152    0.879    
deptJ       -0.2815172  0.4116777  -0.684    0.494    
deptk        0.0124521  0.4104311   0.030    0.976    
deptK       -0.2431624  0.4123474  -0.590    0.555    
deptL        0.0468000  0.4169648   0.112    0.911    
deptm        0.0224798  0.4099682   0.055    0.956    
deptM       -0.4039440  0.4099067  -0.985    0.324    
deptn        0.1487363  0.4111080   0.362    0.718    
deptN        0.1670000  0.4139469   0.403    0.687    
depto       -0.3616667  0.4255629  -0.850    0.395    
deptO        0.0066856  0.4100242   0.016    0.987    
deptp       -0.0139370  0.4120744  -0.034    0.973    
deptP       -0.1140000  0.4249077  -0.268    0.788    
deptq        0.0001132  0.4104076   0.000    1.000    
deptQ       -0.0644094  0.4120744  -0.156    0.876    
deptR       -0.0381579  0.4110139  -0.093    0.926    
depts       -0.0154839  0.4218507  -0.037    0.971    
deptS       -0.0247500  0.4139469  -0.060    0.952    
deptt       -0.0126923  0.4166562  -0.030    0.976    
deptT       -0.2733962  0.4165106  -0.656    0.512    
deptU       -0.1136842  0.4298486  -0.264    0.791    
deptV       -0.0242500  0.4189646  -0.058    0.954    
deptW       -0.0507164  0.4100863  -0.124    0.902    
deptX       -0.1189865  0.4116209  -0.289    0.773    
deptY        0.0814894  0.4174763   0.195    0.845    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5782 on 5670 degrees of freedom
  (437 observations deleted due to missingness)
Multiple R-squared:  0.06037,   Adjusted R-squared:  0.05407 
F-statistic: 9.586 on 38 and 5670 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We have statistically significant evidence of a relationship between department and course grades at a significance level of 0.05 (p-value &lt; 2.2 x <span class="math inline">\(10^{-16}\)</span>). We reject the null hypothesis that there is no relationship between course grade and department.</p>
<ol start="3" type="a">
<li></li>
</ol>
<p><em>None</em> of the individual p-values for department are significant! These p-values tell us about whether or not there is a statistically significant difference in course grades between each respective department and the <em>reference</em> department (Department “A”). This doesn’t contradict our answer to part (b) because there are different hypothesis tests that answer different questions!</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Leslie Myint, 2024<br> All content licensed under <img src="https://static.thenounproject.com/png/70967-200.png" height="20"> (<a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>)</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Site built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>