---
title: "Schedule"
sidebar: false
html-table-processing: none
---

# Overview

```{=html}
<table class="tabsched"><thead>
  <tr>
    <th class="topleft" style="width:13%">Week</th>
    <th class="topleft" style="width:22%">Monday</th>
    <th class="topleft" style="width:22%">Wednesday</th>
    <th class="topleft" style="width:22%">Friday</th>
    <th class="topleft" style="width:21%">Announcements</th>
  </tr></thead>
<tbody>
  <tr>
    <td class="topleft">1 (9/2 - 9/6)</td>
    <td class="topleft"></td>
    <td class="topleft">First day of class</td>
    <td class="topleft">
        Univariate visualization and summaries<br>
        <b>Checkpoint 1 due 11:30am<b>
    </td>
    <td class="topleft"></td>
  </tr>
  <tr>
    <td class="topleft">2 (9/9 - 9/13)</td>
    <td class="topleft">Introduction to simple linear regression</td>
    <td class="topleft">
        Simple linear regression: formalizing concepts<br>
        <b>Checkpoint 2 due 11:30am<b>
    </td>
    <td class="topleft">Time to work on PP1</td>
    <td class="topleft"><b>PP1 due Friday 9/13 at 5pm</b></td>
  </tr>
  <tr>
    <td class="topleft">3 (9/16 - 9/20)</td>
    <td class="topleft">
        Model evaluation<br>
        <b>Checkpoint 3 due 11:30am<b>
    </td>
    <td class="topleft">
        Variable transformations<br>
        <b>Checkpoint 4 due 11:30am<b>
    </td>
    <td class="topleft">
        Data-finding activity with Mac librarians<br>
        <b>Project Group Preferences survey due 5pm<b>
    </td>
    <td class="topleft"><b>PP2 due Friday 9/20 at 5pm</b></td>
  </tr>
  <tr>
    <td class="topleft">4 (9/23 - 9/27)</td>
    <td class="topleft">
        Categorical predictors<br>
        <b>Checkpoint 5 due 11:30am<b>
    </td>
    <td class="topleft">Multiple predictors in linear regression</td>
    <td class="topleft"><b>Quiz 1</b> (1 hour in class)</td>
    <td class="topleft">No Practice Problems this week, but PP3 due next Friday</td>
  </tr>
  <tr>
    <td class="topleft">5 (9/30 - 10/4)</td>
    <td class="topleft">
        Multiple linear regression: principles<br>
        <b>Checkpoint 6 due 11:30am<b>
    </td>
    <td class="topleft">
        Multiple linear regression: confounding<br>
        <b>Checkpoint 7 due 11:30am<b>
    </td>
    <td>Work day</td>
    <td class="topleft"><b>PP3 due Friday 10/4 at 5pm</b></td>
  </tr>
  <tr>
    <td class="topleft">6 (10/4 - 10/11)</td>
    <td class="topleft">
        Introduction to interaction models
    </td>
    <td class="topleft">
        Practice with interaction models<br>
        <b>Checkpoint 8 due 11:30am<b>
    </td>
    <td>No class today (Leslie will be at a workshop) but feel free to use the classroom to work with your project groups</td>
    <td class="topleft"><b>PP4 due Friday 10/11 at 5pm</b></td>
  </tr>
  <tr>
    <td class="topleft">7 (10/14 - 10/18)</td>
    <td class="topleft">
        Model building (Part 1)<br>
        <b>Checkpoint 9 due 11:30am<b>
    </td>
    <td class="topleft">
        Model building (Part 2)
    </td>
    <td>Fall Break!</td>
    <td class="topleft"><b>Project Checkpoint 1 due Wednesday 10/16 at 5pm</b></td>
  </tr>
  <tr>
    <td class="topleft">8 (10/21 - 10/25)</td>
    <td class="topleft">
        Probability and Odds<br>
        <b>Checkpoint 10 due 11:30am<b>
    </td>
    <td class="topleft">
        Simple logistic regression<br>
        <b>Checkpoint 11 due 11:30am<b>
    </td>
    <td class="topleft">
        Multiple logistic regression and evaluation<br>
        <b>Checkpoint 12 due 11:30am<b>
    </td>
    <td class="topleft"><b>PP5 due Friday 10/25 at 5pm</b></td>
  </tr>
  <tr>
    <td class="topleft">9 (10/28 - 11/1)</td>
    <td class="topleft">
        Tools for inference (part 1)<br>
        <b>Checkpoint 13 due 11:30am<b>
    </td>
    <td class="topleft">
        Tools for inference (part 2)<br>
        <b>Checkpoint 14 due 11:30am<b>
    </td>
    <td class="topleft">
        <b>Quiz 2</b> (1 hour in class)
    </td>
    <td class="topleft"></td>
  </tr>
</tbody>
</table>
```



# Weekly details

::: {.callout-tip icon=false collapse="true" title="Week 1: 9/2 - 9/6 (Data fundamentals, univariate visualization and summaries)"}
#### Announcements

Welcome (back) to campus!

#### Wednesday (9/4)

Before class:

- Review the course [syllabus](syllabus.qmd)
- Familiarize yourself with Moodle and the course website
- Complete the [Welcome survey](https://docs.google.com/forms/d/e/1FAIpQLSe7RhOK_7B3XgKNfJ94gdRjftEZjqOtHotYeqF1__B-c_uhIQ/viewform?usp=sf_link)
- Listen to the first episode of the [Sold a Story podcast](https://features.apmreports.org/sold-a-story/) (Episode 1: The Problem) (~30 minutes). This will provide some useful context for what we explore on our first day together.

#### Friday (9/6)

Before class:

- Complete all required steps on the [R Resources](r_resources.qmd) page
- Complete the [Welcome survey](https://docs.google.com/forms/d/e/1FAIpQLSe7RhOK_7B3XgKNfJ94gdRjftEZjqOtHotYeqF1__B-c_uhIQ/viewform?usp=sf_link) (if you haven’t already!)
- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=130247) (CP1) on Moodle
    - Do either the readings or videos for the Day 2 Activity (see Moodle checkpoint description for links to the readings and videos)
    - Due 30 minutes before class today (11:30am on 9/6)
:::

::: {.callout-tip icon=false collapse="true" title="Week 2: 9/9 - 9/13 (Simple linear regression)"}
#### Announcements

- [Practice Problems #1 (PP1)](assignments/pp1.qmd) due Friday 9/13 at 5pm

#### Monday (9/9)

Before class:

- Review material as needed
- No checkpoint today!

#### Wednesday (9/11)

Before class:

- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=133478) (CP2) on Moodle
    - Do either the readings or videos (see Moodle checkpoint description for links to the readings and videos)
    - Due 30 minutes before class today (11:30am on 9/11)

#### Friday (9/13)

Before class:

- Review material as needed
- Work on [Practice Problems #1 (PP1)](assignments/pp1.qmd). We will also have time in class to work on them.

:::

::: {.callout-tip icon=false collapse="true" title="Week 3: 9/16 - 9/20 (Simple linear regression: model evaluation and variable transformations)"}
#### Announcements

- [Practice Problems #2 (PP2)](assignments/pp2.qmd) due Friday 9/20 at 5pm
- [Project Group Preferences Survey](https://docs.google.com/forms/d/e/1FAIpQLSeqclT9Eb7yQZs-_N7Qn1b-NQYJ7pB0PktPKkRIwa3w1s0Ldw/viewform?usp=sf_link) due Friday 9/20 at 5pm
    - This is a short survey to help me determine groups for the course project.
- Quiz 1 is next Friday 9/27 and covers Activities 1-7 (Data Fundamentals to Simple Linear Regression: Categorical Predictors, which we'll talk about next Monday.)

#### Monday (9/16)

Before class:

- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=135166) (CP3) on Moodle. 
    - See checkpoint description for links to the readings/videos.
    - Due 30 minutes before class today (11:30am).

#### Wednesday (9/18)

Before class:

- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=135661) (CP4) on Moodle. 
    - See checkpoint description for links to the readings/videos.
    - Due 30 minutes before class today (11:30am).

#### Friday (9/20)

Before class

- Think about an area that you might want to explore for the [course project](project.qmd). Macalester's librarians will be coming in to lead a workshop on finding data.


:::

::: {.callout-tip icon=false collapse="true" title="Week 4: 9/23 - 9/27 (Simple linear regression: categorical predictors)"}
#### Announcements

- No Practice Problems due this week to allow time to study for Quiz 1 this Friday 9/27.
- For a reminder about quiz format, see [this part](syllabus.qmd#quizzes) of the syllabus.

#### Monday (9/23)

Before class:

- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=137074) (CP5) on Moodle. 
    - See checkpoint description for links to the readings/videos.
    - Due 30 minutes before class today (11:30am).

#### Wednesday (9/25)

Before class:

- Review material as needed
- No checkpoint today!

#### Friday (9/27)

Quiz 1 (1 hour in class)

:::

::: {.callout-tip icon=false collapse="true" title="Week 5: 9/30 - 10/4 (Multiple linear regression: confounding)"}
#### Announcements

- [Practice Problems #3 (PP3)](assignments/pp3.qmd) due Friday 10/4 at 5pm
- Take a look at [project group assignments](https://moodle.macalester.edu/mod/url/view.php?id=138952) posted on Moodle.
    - Work on connecting with your team, finding a dataset, and working on Project Checkpoint 1.
    - Wednesday, October 16: Project Checkpoint 1 due (ignore the Friday, October 11 mentioned in the Google Doc description of the project at the top of the [project page](project.qmd))

#### Monday (9/30)

Before class:

- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=137214) (CP6) on Moodle.
    - See checkpoint description for links to the readings/videos.
    - Due 30 minutes before class today (11:30am).

#### Wednesday (10/2)

Before class:

- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=138420) (CP7) on Moodle.
    - See checkpoint description for links to the readings/videos.
    - Due 30 minutes before class today (11:30am).

#### Friday (10/4)

Time to work on practice problems, project in class

:::

::: {.callout-tip icon=false collapse="true" title="Week 6: 10/7 - 10/11 (Multiple linear regression: interaction)"}
#### Announcements

- Intro to R/RStudio Workshop, Thursday, Oct 10, noon-1pm, Library 250
    - Hosted by our MSCS department R preceptor!
- Quiz 1, PP1, PP2 corrections due Wednesday 10/9 on [Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=139742)
- [Practice Problems #4 (PP4)](assignments/pp4.qmd) due Friday 10/11 at 5pm
- Take a look at [project group assignments](https://moodle.macalester.edu/mod/url/view.php?id=138952) posted on Moodle.
    - Work on connecting with your team, finding a dataset, and working on Project Checkpoint 1.
    - Wednesday, October 16: Project Checkpoint 1 due (ignore the Friday, October 11 mentioned in the Google Doc description of the project at the top of the [project page](project.qmd))

#### Monday (10/7)

Before class:

- Review material as needed
- No checkpoint today!

#### Wednesday (10/9)

Before class:

- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=138985) (CP8) on Moodle.
    - See checkpoint description for links to the readings/videos.
    - Due 30 minutes before class today (11:30am).

#### Friday (10/11)

No class today - Leslie will be at a workshop. Feel free to use the classroom to meet with your project groups

:::

::: {.callout-tip icon=false collapse="true" title="Week 7: 10/14 - 10/18 (Multiple linear regression: model building) (Fall Break)"}
#### Announcements

- Wednesday, October 16: [Project Checkpoint 1](https://moodle.macalester.edu/mod/assign/view.php?id=140986) due on Moodle (only one team member per group needs to submit) ([Group assignments]([project group assignments](https://moodle.macalester.edu/mod/url/view.php?id=138952)))
- [Practice Problems #5 (PP5)](assignments/pp5.qmd) due Friday 10/25 at 5pm (1 week AFTER Fall Break)

#### Monday (10/14)

Before class:

- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=140962) (CP9) on Moodle.
    - See checkpoint description for links to the readings/videos.
    - Due 30 minutes before class today (11:30am).

#### Wednesday (10/16)

Before class:

- Review material as needed
- No checkpoint today!

#### Friday (10/18)

Fall Break!

:::

::: {.callout-tip icon=false collapse="false" title="Week 8: 10/21 - 10/25 (Logistic regression)"}
#### Announcements

- [Practice Problems #5 (PP5)](assignments/pp5.qmd) due Friday 10/25 at 5pm
- Start reviewing for Quiz 2 next Friday 11/1.
- MSCS & Society Lecture, Wednesday, 4:40-5:40pm, JBD
    - See [here](https://drive.google.com/file/d/1hxrCNHRS_JQm1_W1JtDF8aYrlEAp102m/view?usp=drive_link) for a flyer!

#### Monday (10/21)

Before class:

- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=141468) (CP10) on Moodle.
    - See checkpoint description for links to the readings/videos.
    - Due 30 minutes before class today (11:30am).

#### Wednesday (10/23)

Before class:

- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=142075) (CP11) on Moodle.
    - See checkpoint description for links to the readings/videos.
    - Due 30 minutes before class today (11:30am).

#### Friday (10/25)

Before class:

- Complete today's [checkpoint](https://moodle.macalester.edu/mod/quiz/view.php?id=142076) (CP12) on Moodle.
    - See checkpoint description for links to the readings/videos.
    - Due 30 minutes before class today (11:30am).

:::

::: {.callout-tip icon=false collapse="true" title="Week 9: 10/28 - 11/1 (Tools for statistical inference)"}
#### Announcements

#### Monday

Before class:

#### Wednesday

Before class:

#### Friday

Quiz 2 (1 hour in class)

:::

::: {.callout-tip icon=false collapse="true" title="Week 10: 11/4 - 11/8 (Confidence intervals)"}
#### Announcements

#### Monday

Before class:

#### Wednesday

Before class:

#### Friday

Before class:

:::

::: {.callout-tip icon=false collapse="true" title="Week 11: 11/11 - 11/15 (Hypothesis testing)"}
#### Announcements

#### Monday

Before class:

#### Wednesday

Before class:

#### Friday

Before class:

:::

::: {.callout-tip icon=false collapse="true" title="Week 12: 11/18 - 11/22 (Hypothesis testing)"}
#### Announcements

#### Monday

Before class:

#### Wednesday

Before class:

#### Friday

Before class:

:::

::: {.callout-tip icon=false collapse="true" title="Week 13: 11/25 - 11/29 (Hypothesis testing, p-values) (Thanksgiving Break)"}
#### Announcements

#### Monday

Before class:

#### Wednesday

Before class:

#### Friday

Before class:

:::

::: {.callout-tip icon=false collapse="true" title="Week 14: 12/2 - 12/6 (Project work)"}
#### Announcements

#### Monday

Before class:

#### Wednesday

Before class:

#### Friday

Before class:

:::

::: {.callout-tip icon=false collapse="true" title="Week 15: 12/9 - 12/13 (Project work, paper, and presentations)"}
#### Announcements

#### Monday

Before class:

#### Wednesday

(Last day of class)

Before class:

:::

